from typing import TYPE_CHECKING
from BaseClasses import Location
from . import items
from dataclasses import dataclass
from enum import Enum, auto
from .regions import WSRRegionName

if TYPE_CHECKING:
    from .world import WSRWorld

class WSRLocation(Location):
    game = "Witchspring R"

class LocationGroup(Enum):
    CHEST = auto()
    FIELDITEM = auto()
    RECIPE = auto()
    EVENT = auto()
    BLESSING = auto()

@dataclass
class WSRLocationData:
    code: int
    region: str
    group: LocationGroup
    scene: str
    game_id: str
    method_index: int | None = None
    vanilla_item: str = ""
    vanilla_quantity: int = 1
    repeat_behavior: str = "none"
    # Optional per-location chapter floor. Use when a check lives in an early region
    # but only fires later in the story (e.g. a cutscene that requires a later chapter).
    # should_include_location takes max(region_required_chapter, min_chapter).
    min_chapter: int | None = None
    # Missable / one-time checks that can be permanently lost. Marked EXCLUDED so the
    # fill only places filler here and a player can never be required to grab it.
    excluded: bool = False
    

location_table = {
    "Arua Temple – Room Behind Sealing Stone": WSRLocationData(
        code=200001,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua_Room1",
        game_id="ChestItem",
        vanilla_item="Book_Level_SubCircle",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Lalaque Village - Brida House": WSRLocationData(
        code=200002,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="House_LalauqeVillageSet",
        game_id="FieldItem_LalaqueApple (1)",
        vanilla_item="LalaqueAppleDark",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Village - Novel House Floor": WSRLocationData(
        code=200003,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="House_LalauqeVillageSet",
        game_id="FieldItem_LalaqueApple",
        vanilla_item="LalaqueApple",
        vanilla_quantity=8,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Village - Sara House": WSRLocationData(
        code=200004,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="House_LalauqeVillageSet",
        game_id="FieldItem_LalaqueApple (2)",
        vanilla_item="LalaqueApple",
        vanilla_quantity=7,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Village - Novel House Chest": WSRLocationData(
        code=200005,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.CHEST,
        scene="House_LalauqeVillageSet",
        game_id="ChestItem (3)",
        vanilla_item="LalaqueAppleDark",
        vanilla_quantity=3,
        repeat_behavior="none",
    ),

    "Lalaque Village - Farm 1": WSRLocationData(
        code=200006,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="Village_Lalaque_North",
        game_id="Item_Carrot",
        vanilla_item="Carrot",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Village - Farm 2": WSRLocationData(
        code=200007,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="Village_Lalaque_North",
        game_id="Item_Carrot (1)",
        vanilla_item="Carrot",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Village - Farm 3": WSRLocationData(
        code=200008,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="Village_Lalaque_North",
        game_id="Item_Carrot (2)",
        vanilla_item="Carrot",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Village - Anna's House": WSRLocationData(
        code=200009,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.CHEST,
        scene="House_Anna",
        game_id="ChestItem",
        vanilla_item="Book_Level_Anna",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Entrance - Item Across Bridge": WSRLocationData(
        code=200010,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine",
        game_id="Item_Sparkor",
        vanilla_item="Sparkor",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Entrance - Item East of Spawn": WSRLocationData(
        code=200011,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine",
        game_id="Item_Sparkor2",
        vanilla_item="Sparkor",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Entrance - North West Item": WSRLocationData(
        code=200012,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine",
        game_id="Item_Sparkor2 (1)",
        vanilla_item="Sparkor",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - Middle Item": WSRLocationData(
        code=200013,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_Sparkor3 (3)",
        vanilla_item="Sparkor",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - West Item": WSRLocationData(
        code=200014,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_Sparkor3",
        vanilla_item="Sparkor",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - East Bottom Item": WSRLocationData(
        code=200015,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_Sparkor3 (1)",
        vanilla_item="Sparkor",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - North Carts": WSRLocationData(
        code=200016,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_IronOre (1)",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - East Top Item": WSRLocationData(
        code=200017,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_Sparkor3 (2)",
        vanilla_item="Sparkor",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - West Carts": WSRLocationData(
        code=200018,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_IronOre (2)",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - East Carts": WSRLocationData(
        code=200019,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_IronOre (3)",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - Before Carts": WSRLocationData(
        code=200020,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="Item_IronOre",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 1 - Carts Chest": WSRLocationData(
        code=200021,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_1",
        game_id="ChestItem",
        vanilla_item="SmallBomb",
        vanilla_quantity=5,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Zone 2 - Back Center Item": WSRLocationData(
        code=200022,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="Item_IronOre (1)",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 2 - Right Item Across Chasm": WSRLocationData(
        code=200023,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="Item_IronOre (4)",
        vanilla_item="IronOre",
        vanilla_quantity=5,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 2 - Back Right Item": WSRLocationData(
        code=200024,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="Item_IronOre",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 2 - Left Item Across Chasm": WSRLocationData(
        code=200025,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="Item_IronOre (5)",
        vanilla_item="IronOre",
        vanilla_quantity=7,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 2 - Near Entrance Across Chasm": WSRLocationData(
        code=200026,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="Item_IronOre (3)",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 2 - Near Teleport": WSRLocationData(
        code=200027,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="Item_IronOre (2)",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 2 - Chest Across Chasm": WSRLocationData(
        code=200028,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_2",
        game_id="ChestItem (1)",
        vanilla_item="PowerSpring",
        vanilla_quantity=20,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Zone 3 - Right Top Item": WSRLocationData(
        code=200029,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_3",
        game_id="Item_IronOre (3)",
        vanilla_item="IronOre",
        vanilla_quantity=5,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 3 - Right Bottom Item": WSRLocationData(
        code=200030,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_3",
        game_id="Item_IronOre (2)",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 3 - Far Left Item": WSRLocationData(
        code=200031,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_3",
        game_id="Item_IronOre (1)",
        vanilla_item="IronOre",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 3 - Closer Left Item": WSRLocationData(
        code=200032,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_3",
        game_id="Item_IronOre",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 3 - Left Chest": WSRLocationData(
        code=200033,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_3",
        game_id="ChestItem",
        vanilla_item="SmallBomb3",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Zone 4 - Puzzle Start": WSRLocationData(
        code=200034,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_4",
        game_id="Item_IronOre (2)",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 4 - Puzzle Item 2": WSRLocationData(
        code=200035,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_4",
        game_id="Item_IronOre (1)",
        vanilla_item="IronOre",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 4 - Puzzle End": WSRLocationData(
        code=200036,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_4",
        game_id="Item_IronOre (3)",
        vanilla_item="IronOre",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 4 - Puzzle Item 3": WSRLocationData(
        code=200037,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_4",
        game_id="Item_IronOre",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Zone 4 - Chest 1": WSRLocationData(
        code=200038,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_4",
        game_id="ChestItem",
        vanilla_item="BombLine",
        vanilla_quantity=5,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Zone 4 - Chest 2": WSRLocationData(
        code=200039,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_4",
        game_id="ChestItem (1)",
        vanilla_item="BombLine",
        vanilla_quantity=3,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Ore Storehouse - Left Closer Item": WSRLocationData(
        code=200040,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_Store",
        game_id="Item_IronOre (5)",
        vanilla_item="IronOre",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Ore Storehouse - Right Item": WSRLocationData(
        code=200041,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_Store",
        game_id="Item_IronOre (6)",
        vanilla_item="IronOre",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Ore Storehouse - Back Item": WSRLocationData(
        code=200042,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_Store",
        game_id="Item_IronOre (4)",
        vanilla_item="IronOre",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Ore Storehouse - Left Further Item": WSRLocationData(
        code=200043,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Lalaque_Mine_CannaArea_Store",
        game_id="Item_IronOre (3)",
        vanilla_item="IronOre",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Mine - Ore Storehouse - Chest 1": WSRLocationData(
        code=200044,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_Store",
        game_id="ChestItem (3)",
        vanilla_item="Book_Bomb",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Lalaque Mine - Ore Storehouse - Chest 2": WSRLocationData(
        code=200045,
        region=WSRRegionName.LALAQUE_MINE,
        group=LocationGroup.CHEST,
        scene="Cave_Lalaque_Mine_CannaArea_Store",
        game_id="ChestItem (2)",
        vanilla_item="SmallBomb2",
        vanilla_quantity=5,
        repeat_behavior="none",
    ),

    "Lalaque Forest - Warriors Tent - Top Item": WSRLocationData(
        code=200046,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Lalaque",
        game_id="FieldItem_WarriorTent",
        vanilla_item="Gold",
        vanilla_quantity=500,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Forest - Warriors Tent - Bottom Item": WSRLocationData(
        code=200047,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Lalaque",
        game_id="FieldItem_WarriorTent",
        vanilla_item="Gold",
        vanilla_quantity=400,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Forest - Warriors Tent - Middle Item": WSRLocationData(
        code=200048,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Lalaque",
        game_id="FieldItem_WarriorTent",
        vanilla_item="Gold",
        vanilla_quantity=300,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Forest - Southeast - Middle Item": WSRLocationData(
        code=200049,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Lalaque_EastSouth",
        game_id="FieldItem_LalaqueApple",
        vanilla_item="LalaqueApple",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Forest - Southeast - Bottom Item": WSRLocationData(
        code=200050,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Lalaque_EastSouth",
        game_id="FieldItem_LalaqueApple",
        vanilla_item="LalaqueApple",
        vanilla_quantity=5,
        repeat_behavior="vanilla_after_first",
    ),

    "Lalaque Forest - Southeast - Top Item": WSRLocationData(
        code=200051,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Lalaque_EastSouth",
        game_id="FieldItem_LalaqueApple",
        vanilla_item="LalaqueApple",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lions Plain - Central - Right Item": WSRLocationData(
        code=200052,
        region=WSRRegionName.LIONS_PLAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_LionField_Mid",
        game_id="Item_Water (2)",
        vanilla_item="CleanWaterBall",
        vanilla_quantity=5,
        repeat_behavior="vanilla_after_first",
    ),

    "Lions Plain - Central - Top Item": WSRLocationData(
        code=200053,
        region=WSRRegionName.LIONS_PLAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_LionField_Mid",
        game_id="Item_Water (1)",
        vanilla_item="CleanWaterBall",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Lions Plain - Central - Bottom Item": WSRLocationData(
        code=200054,
        region=WSRRegionName.LIONS_PLAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_LionField_Mid",
        game_id="Item_Water",
        vanilla_item="CleanWaterBall",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Aimhard Temple - Prison - Chest 1": WSRLocationData(
        code=200055,
        region=WSRRegionName.AIMHARD_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Aimhard_UnderPrison2",
        game_id="ChestItem1",
        vanilla_item="BigGuardian",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Aimhard Temple - Prison - Chest 2": WSRLocationData(
        code=200056,
        region=WSRRegionName.AIMHARD_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Aimhard_UnderPrison2",
        game_id="ChestItem2",
        vanilla_item="SmalGuardian",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Aimhard Temple - Prison - Chest 3": WSRLocationData(
        code=200057,
        region=WSRRegionName.AIMHARD_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Aimhard_UnderPrison3",
        game_id="ChestItem1",
        vanilla_item="GuardianGlove",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Aimhard Temple - Prison - Chest 4": WSRLocationData(
        code=200058,
        region=WSRRegionName.AIMHARD_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Aimhard_UnderPrison3",
        game_id="ChestItem1 (1)",
        vanilla_item="Sword_SoulOff",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Laoba Mountain - Warrior Camp - Back Right Corner": WSRLocationData(
        code=200059,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Boar2",
        game_id="Item_DryLeaf_3 (4)",
        vanilla_item="Gold",
        vanilla_quantity=1000,
        repeat_behavior="vanilla_after_first",
    ),

    "Laoba Mountain - Warrior Camp - Inbetween Tents": WSRLocationData(
        code=200060,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Boar2",
        game_id="Item_DryLeaf_3 (5)",
        vanilla_item="Gold",
        vanilla_quantity=1000,
        repeat_behavior="vanilla_after_first",
    ),

    "Laoba Mountain - Warrior Camp - Tree Near Water": WSRLocationData(
        code=200061,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Boar2",
        game_id="Item_DryLeaf_3 (2)",
        vanilla_item="Gold",
        vanilla_quantity=500,
        repeat_behavior="vanilla_after_first",
    ),

    "Laoba Mountain - Warrior Camp - Behind Command Tent": WSRLocationData(
        code=200062,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.FIELDITEM,
        scene="Forest_Boar2",
        game_id="Item_DryLeaf_3 (3)",
        vanilla_item="Gold",
        vanilla_quantity=1000,
        repeat_behavior="vanilla_after_first",
    ),

    "Laoba Mountain - Warrior Camp - Chest 1": WSRLocationData(
        code=200063,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.CHEST,
        scene="Forest_Boar2",
        game_id="ChestItem2 (2)",
        vanilla_item="Gold",
        vanilla_quantity=5000,
        repeat_behavior="none",
    ),

    "Laoba Mountain - Warrior Camp - Chest 2": WSRLocationData(
        code=200064,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.CHEST,
        scene="Forest_Boar2",
        game_id="ChestItem2 (4)",
        vanilla_item="Gold",
        vanilla_quantity=10000,
        repeat_behavior="none",
    ),

    "Laoba Mountain - Warrior Camp - Chest 3": WSRLocationData(
        code=200065,
        region=WSRRegionName.LAOBA_MOUNTAIN,
        group=LocationGroup.CHEST,
        scene="Forest_Boar2",
        game_id="ChestItem2 (3)",
        vanilla_item="Gold",
        vanilla_quantity=10000,
        repeat_behavior="none",
    ),

    #"CHECKME": WSRLocationData(
    #    code=200066,
    #    region=WSRRegionName.VAVELIA_ROAD,
    #    group=LocationGroup.FIELDITEM,
    #    scene="Road_Babellia_WarriorCamp",
    #    game_id="Item_DryLeaf_3 (4)",
    #    vanilla_item="Gold",
    #    vanilla_quantity=700,
    #    repeat_behavior="vanilla_after_first",
    #),

    "Vavelia Road - Warrior Camp - Command Tent": WSRLocationData(
        code=200067,
        region=WSRRegionName.VAVELIA_ROAD,
        group=LocationGroup.FIELDITEM,
        scene="Road_Babellia_WarriorCamp",
        game_id="Item_DryLeaf_3 (3)",
        vanilla_item="Gold",
        vanilla_quantity=800,
        repeat_behavior="vanilla_after_first",
    ),

    #"CHECKME2": WSRLocationData(
    #    code=200068,
    #    region=WSRRegionName.VAVELIA_ROAD,
    #    group=LocationGroup.FIELDITEM,
    #    scene="Road_Babellia_WarriorCamp",
    #    game_id="Item_DryLeaf_3 (2)",
    #    vanilla_item="Gold",
    #    vanilla_quantity=700,
    #    repeat_behavior="vanilla_after_first",
    #),

    "Vavelia Road - Warrior Camp - By Tents": WSRLocationData(
        code=200069,
        region=WSRRegionName.VAVELIA_ROAD,
        group=LocationGroup.FIELDITEM,
        scene="Road_Babellia_WarriorCamp",
        game_id="Item_DryLeaf_3 (6)",
        vanilla_item="Gold",
        vanilla_quantity=500,
        repeat_behavior="vanilla_after_first",
    ),

    #"CHECKME3": WSRLocationData(
    #    code=200070,
    #    region=WSRRegionName.VAVELIA_ROAD,
    #    group=LocationGroup.FIELDITEM,
    #    scene="Road_Babellia_WarriorCamp",
    #    game_id="Item_DryLeaf_3 (5)",
    #    vanilla_item="Gold",
    #    vanilla_quantity=700,
    #    repeat_behavior="vanilla_after_first",
    #),

    "Vavelia Road - Warrior Camp - Command Chest 1": WSRLocationData(
        code=200071,
        region=WSRRegionName.VAVELIA_ROAD,
        group=LocationGroup.CHEST,
        scene="Road_Babellia_WarriorCamp",
        game_id="ChestItem2 (4)",
        vanilla_item="Gold",
        vanilla_quantity=10000,
        repeat_behavior="none",
    ),

    "Vavelia Road - Warrior Camp - Command Chest 2": WSRLocationData(
        code=200072,
        region=WSRRegionName.VAVELIA_ROAD,
        group=LocationGroup.CHEST,
        scene="Road_Babellia_WarriorCamp",
        game_id="ChestItem2 (3)",
        vanilla_item="Gold",
        vanilla_quantity=20000,
        repeat_behavior="none",
    ),

    "Death Squad Lair - Sleeping Quarters - Chest Behind Beds": WSRLocationData(
        code=200073,
        region=WSRRegionName.DEATH_SQUAD,
        group=LocationGroup.CHEST,
        scene="Cave_BoarMountain",
        game_id="ChestItem",
        vanilla_item="Gold",
        vanilla_quantity=14000,
        repeat_behavior="none",
    ),

    "Elysion Plain - Blocked Path - Chest": WSRLocationData(
        code=200074,
        region=WSRRegionName.ELYSION_PLAIN,
        group=LocationGroup.RECIPE,
        scene="Forest_Elicion_Blocked",
        game_id="ChestItem",
        vanilla_item="StrengthSoup",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Vavelia Village - Village Proper - Ground by Bridge": WSRLocationData(
        code=200075,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="Village_Vabellia_Enter",
        game_id="Field_item_BigKey",
        vanilla_item="Key_Big",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Vavelia Village - Village Proper - Ground by Other Bridge": WSRLocationData(
        code=200076,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="Village_Vabellia_InnerSet",
        game_id="Field_item_BigKey",
        vanilla_item="Gold",
        vanilla_quantity=6000,
        repeat_behavior="vanilla_after_first",
    ),

    "Vavelia Village - Houses - Tavern?": WSRLocationData(
        code=200077,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.FIELDITEM,
        scene="Village_Vabellia_InnerSet",
        game_id="FieldItem_LalaqueApple",
        vanilla_item="",
        vanilla_quantity=0,
        repeat_behavior="vanilla_after_first",
    ),

    "Vavelia Village - Houses - Chest 1": WSRLocationData(
        code=200078,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.CHEST,
        scene="Village_Vabellia_InnerSet",
        game_id="ChestItem (4)",
        vanilla_item="WarriorPotionMP",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Vavelia Village - Houses - Chest 2": WSRLocationData(
        code=200079,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.CHEST,
        scene="Village_Vabellia_InnerSet",
        game_id="ChestItem",
        vanilla_item="Gold",
        vanilla_quantity=5000,
        repeat_behavior="none",
    ),

    "Vavelia Village - Houses - Chest 3": WSRLocationData(
        code=200080,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.CHEST,
        scene="Village_Vabellia_InnerSet",
        game_id="ChestItem (3)",
        vanilla_item="WarriorPotionHP",
        vanilla_quantity=4,
        repeat_behavior="none",
    ),

    "Vavelia Village - Houses - Chest 4": WSRLocationData(
        code=200081,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.CHEST,
        scene="Village_Vabellia_InnerSet",
        game_id="ChestItem (1)",
        vanilla_item="Gold",
        vanilla_quantity=10000,
        repeat_behavior="none",
    ),

    "Vavelia Village - Houses - Chest 5": WSRLocationData(
        code=200082,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.CHEST,
        scene="Village_Vabellia_InnerSet",
        game_id="ChestItem (2)",
        vanilla_item="Gold",
        vanilla_quantity=7000,
        repeat_behavior="none",
    ),

    "Snow Field - Behind 5 Yeti": WSRLocationData(
        code=200083,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand",
        game_id="Item_EternalIce (4)",
        vanilla_item="EternalIce",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Item Below Teleport": WSRLocationData(
        code=200084,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand",
        game_id="Item_EternalIce (2)",
        vanilla_item="EternalIce",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Behind 2 Yeti": WSRLocationData(
        code=200085,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand",
        game_id="Item_EternalIce (1)",
        vanilla_item="EternalIce",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Next to Item Below Teleport": WSRLocationData(
        code=200086,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand",
        game_id="Item_EternalIce",
        vanilla_item="EternalIce",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Above Teleport Behind Ramp": WSRLocationData(
        code=200087,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand",
        game_id="Item_EternalIce (3)",
        vanilla_item="EternalIce",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Ice Cave - Far Right": WSRLocationData(
        code=200088,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand_Cave",
        game_id="Item_EternalIce (2)",
        vanilla_item="EternalIce",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Ice Cave - Behind Ramp to Ice Giant": WSRLocationData(
        code=200089,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand_Cave",
        game_id="Item_EternalIce",
        vanilla_item="EternalIce",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Ice Cave - By Bridge": WSRLocationData(
        code=200090,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand_Cave",
        game_id="Item_EternalIce (3)",
        vanilla_item="EternalIce",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Ice Cave - Blocked By Schwitz": WSRLocationData(
        code=200091,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.FIELDITEM,
        scene="SnowLand_Cave",
        game_id="Item_EternalIce (1)",
        vanilla_item="EternalIce",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Snow Field - Frozen Altar - Chest": WSRLocationData(
        code=200092,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.CHEST,
        scene="SnowLand_Cave2",
        game_id="ChestItem",
        vanilla_item="Shield_Ice",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Pudding Cave - Entrance - Top Left Item": WSRLocationData(
        code=200093,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding",
        game_id="Item_Stone_Small (3)",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Entrance - Center Item": WSRLocationData(
        code=200094,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding",
        game_id="Item_Stone_Small (1)",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Entrance - Bottom Left Item": WSRLocationData(
        code=200095,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding",
        game_id="Item_Stone_Small (4)",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Entrance - Center Left Item": WSRLocationData(
        code=200096,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding",
        game_id="Item_Stone_Small (2)",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Entrance - Far Right Item": WSRLocationData(
        code=200097,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding",
        game_id="Item_Stone_Small",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Entrance - Chest": WSRLocationData(
        code=200098,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.CHEST,
        scene="Cave_Pudding",
        game_id="ChestItem",
        vanilla_item="PuddingPie",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Pudding Cave - Deep _ Back Left Item": WSRLocationData(
        code=200099,
        region=WSRRegionName.PUDDING_CAVE_2,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding_2",
        game_id="Item_Stone_Small_Blue (3)",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Deep - Right of Teleporter Item": WSRLocationData(
        code=200100,
        region=WSRRegionName.PUDDING_CAVE_2,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding_2",
        game_id="Item_Stone_Small_Blue (2)",
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Deep - Left of Teleporter Item": WSRLocationData(
        code=200101,
        region=WSRRegionName.PUDDING_CAVE_2,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Pudding_2",
        game_id="Item_Stone_Small_Blue (1)",
        vanilla_item="OldLeafPuddingPart",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Pudding Cave - Deep - Top Left Chest": WSRLocationData(
        code=200102,
        region=WSRRegionName.PUDDING_CAVE_2,
        group=LocationGroup.RECIPE,
        scene="Cave_Pudding_2",
        game_id="ChestItem1",
        vanilla_item="StickyPack",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Pudding Cave - Deep - Bottom Left Chest": WSRLocationData(
        code=200103,
        region=WSRRegionName.PUDDING_CAVE_2,
        group=LocationGroup.CHEST,
        scene="Cave_Pudding_2",
        game_id="ChestItem",
        vanilla_item="PuddingPie",
        vanilla_quantity=4,
        repeat_behavior="none",
    ),

    "Pudding Cave - Royal Pudding - Chest": WSRLocationData(
        code=200104,
        region=WSRRegionName.PUDDING_CAVE_3,
        group=LocationGroup.RECIPE,
        scene="Cave_Pudding_3",
        game_id="ChestItem2 (2)",
        vanilla_item="KingQueenPudding",
        vanilla_quantity=0,
        repeat_behavior="none",
    ),

    "Swamp - Item Near Wampleaf": WSRLocationData(
        code=200105,
        region=WSRRegionName.SWAMP,
        group=LocationGroup.FIELDITEM,
        scene="Swamp_1",
        game_id="Item (1)",
        vanilla_item="Frogspawn",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Swamp - Central Item": WSRLocationData(
        code=200106,
        region=WSRRegionName.SWAMP,
        group=LocationGroup.FIELDITEM,
        scene="Swamp_1",
        game_id="Item",
        vanilla_item="Frogspawn",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Swamp - Bottom Item": WSRLocationData(
        code=200107,
        region=WSRRegionName.SWAMP,
        group=LocationGroup.FIELDITEM,
        scene="Swamp_1",
        game_id="Item (2)",
        vanilla_item="Frogspawn",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Swamp - Chest 1": WSRLocationData(
        code=200108,
        region=WSRRegionName.SWAMP,
        group=LocationGroup.CHEST,
        scene="Swamp_1",
        game_id="ChestItem",
        vanilla_item="GoodCookie",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Blackhill Golem Cave - Entrance - Item by Fox Den": WSRLocationData(
        code=200109,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain",
        game_id="Item_Stone_Small_Blue (1)",
        vanilla_item="Stone_Small_Blue",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),

    "Blackhill Golem Cave - Entrance - Item By Entrance": WSRLocationData(
        code=200110,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain",
        game_id="Item_Stone_Small_Blue",
        vanilla_item="Stone_Small_Blue",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Blackhill Golem Cave - Entrance - Chest 1": WSRLocationData(
        code=200111,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE,
        group=LocationGroup.CHEST,
        scene="Cave_Golem_BackMountain",
        game_id="ChestItem2 (2)",
        vanilla_item="AgtStimulus",
        vanilla_quantity=3,
        repeat_behavior="none",
    ),

    "Blackhill Golem Cave - Entrance - Chest 2": WSRLocationData(
        code=200112,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE,
        group=LocationGroup.CHEST,
        scene="Cave_Golem_BackMountain",
        game_id="ChestItem2 (1)",
        vanilla_item="ShieldStone",
        vanilla_quantity=3,
        repeat_behavior="none",
    ),

    "Blackhill Golem Cave - Fox Den - Chest": WSRLocationData(
        code=200113,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FOX,
        group=LocationGroup.RECIPE,
        scene="Cave_Golem_BackMountain_Fox",
        game_id="ChestItem1",
        vanilla_item="FoxOrb",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Blackhill Golem Cave - Fire Cave - Right Item": WSRLocationData(
        code=200114,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain_Fire",
        game_id="Item_FireDust",
        vanilla_item="FireDust",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Blackhill Golem Cave - Fire Cave - Item Near Entrance": WSRLocationData(
        code=200115,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain_Fire",
        game_id="Item_FireDust",
        vanilla_item="FireDust",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Blackhill Golem Cave - Fire Cave - Left Item": WSRLocationData(
        code=200116,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain_Fire",
        game_id="Item_FireDust (1)",
        vanilla_item="FireDust",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Blackhill Golem Cave - Volcano Road - Left Item": WSRLocationData(
        code=200117,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE_2,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain_Fire_2",
        game_id="Item_FireDust",
        vanilla_item="FireDust",
        vanilla_quantity=4,
        repeat_behavior="vanilla_after_first",
    ),

    "Blackhill Golem Cave - Volcano Road - Right Item": WSRLocationData(
        code=200118,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE_2,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Golem_BackMountain_Fire_2",
        game_id="Item_FireDust (1)",
        vanilla_item="FireDust",
        vanilla_quantity=12,
        repeat_behavior="vanilla_after_first",
    ),

    #"CHECKME4": WSRLocationData(
    #    code=200119,
    #    region=WSRRegionName.BLACKHILL_GOLEM_CAVE,
    #    group=LocationGroup.FIELDITEM,
    #    scene="Cave_Golem_BackMountain_Fire_Cow",
    #    game_id="Item_LightningCrystal",
    #    vanilla_item="FireCrystal",
    #    vanilla_quantity=1,
    #    repeat_behavior="vanilla_after_first",
    #),

    "Blackhill Golem Cave - Lava Road - Chest Behind Lava Enemies": WSRLocationData(
        code=200120,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE_3,
        group=LocationGroup.CHEST,
        scene="Cave_Golem_BackMountain_Fire_3",
        game_id="ChestItem2 (2)",
        vanilla_item="FirePendant",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Darkstone Cave - Entrance - Item Near Entrance": WSRLocationData(
        code=200121,
        region=WSRRegionName.DARKSTONE_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Dark",
        game_id="Item_Stone_Small_Blue",
        vanilla_item="DarkStoneSmall",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Darkstone Cave - Entrance - Behind 7 Poison Golems 1": WSRLocationData(
        code=200122,
        region=WSRRegionName.DARKSTONE_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Dark",
        game_id="Item_Stone_Small_Blue (1)",
        vanilla_item="DarkStoneSmall",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Darkstone Cave - Entrance - Behind 7 Poison Golems 2": WSRLocationData(
        code=200123,
        region=WSRRegionName.DARKSTONE_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Dark",
        game_id="Item_Stone_Small_Blue (2)",
        vanilla_item="DarkStoneSmall",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Darkstone Cave - Entrance - Back Item": WSRLocationData(
        code=200124,
        region=WSRRegionName.DARKSTONE_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Dark",
        game_id="Item_Stone_Small_Blue (4)",
        vanilla_item="DarkStoneSmall",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Darkstone Cave - Entrance - Central Left Item": WSRLocationData(
        code=200125,
        region=WSRRegionName.DARKSTONE_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Dark",
        game_id="Item_Stone_Small_Blue (3)",
        vanilla_item="DarkStoneSmall",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Darkstone Cave - Entrance - Central Right Item": WSRLocationData(
        code=200126,
        region=WSRRegionName.DARKSTONE_CAVE,
        group=LocationGroup.FIELDITEM,
        scene="Cave_Dark",
        game_id="Item_Stone_Small_Blue (5)",
        vanilla_item="DarkStoneSmall",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),

    "Elysion Plain - Central - Chest in Abandonded Camp": WSRLocationData(
        code=200127,
        region=WSRRegionName.ELYSION_PLAIN,
        group=LocationGroup.CHEST,
        scene="Forest_Elicion_1",
        game_id="ChestItem",
        vanilla_item="FeatherShoose",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "South Island - Chest 1": WSRLocationData(
        code=200128,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.CHEST,
        scene="Island_Arua",
        game_id="ChestItem1 (1)",
        vanilla_item="LeafBall",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=2,  # swim-only islet; logic-gated on Aged Lalaque Berry (Eison swim mount, Ch2)
    ),

    "South Island - Chest 2": WSRLocationData(
        code=200129,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.CHEST,
        scene="Island_Arua",
        game_id="ChestItem1",
        vanilla_item="SPGrowth",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "South Island - Chest 3": WSRLocationData(
        code=200130,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.RECIPE,
        scene="Island_Arua",
        game_id="ChestItem2 (3)",
        vanilla_item="Cronball",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "South Island - Chest 4": WSRLocationData(
        code=200131,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.CHEST,
        scene="Island_Arua",
        game_id="ChestItem2 (2)",
        vanilla_item="RabbitBread",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "South Island - Chest 5": WSRLocationData(
        code=200132,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.CHEST,
        scene="Island_Arua",
        game_id="ChestItem2 (1)",
        vanilla_item="Meat_RabbitFood",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "South Island - Chest 6": WSRLocationData(
        code=200133,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.CHEST,
        scene="Island_Arua",
        game_id="ChestItem2",
        vanilla_item="TouchClothArmor",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Shipwreck - Armory - Chest 1": WSRLocationData(
        code=200134,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.CHEST,
        scene="ShipWrecked_Cannon",
        game_id="ChestItem1",
        vanilla_item="Book_Ban",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Shipwreck - Armory - Chest 2": WSRLocationData(
        code=200135,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.CHEST,
        scene="ShipWrecked_Cannon",
        game_id="ChestItem (4)",
        vanilla_item="Gold",
        vanilla_quantity=10000,
        repeat_behavior="none",
    ),

    "Shipwreck - Armory - Chest 3": WSRLocationData(
        code=200136,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.CHEST,
        scene="ShipWrecked_Cannon",
        game_id="ChestItem (5)",
        vanilla_item="SmallBomb3",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Shipwreck - Armory - Chest 4": WSRLocationData(
        code=200137,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.CHEST,
        scene="ShipWrecked_Cannon",
        game_id="ChestItem (2)",
        vanilla_item="Gold",
        vanilla_quantity=7000,
        repeat_behavior="none",
    ),

    #"CHECKME5": WSRLocationData(
    #    code=200138,
    #    region=WSRRegionName.SHIPWRECK,
    #    group=LocationGroup.FIELDITEM,
    #    scene="ShipWrecked_Prison",
    #    game_id="Item_JadePaper",
    #    vanilla_item="JadePaper6",
    #    vanilla_quantity=1,
    #    repeat_behavior="none",
    #),

    "Shipwreck - Brig - Chest 1": WSRLocationData(
        code=200139,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.CHEST,
        scene="ShipWrecked_Prison",
        game_id="ChestItem1",
        vanilla_item="Shield_Dark",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Shipwreck - Brig - Chest 2": WSRLocationData(
        code=200140,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.CHEST,
        scene="ShipWrecked_Prison",
        game_id="ChestItem1 (1)",
        vanilla_item="PowerStimuler",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 1": WSRLocationData(
        code=200141,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem (1)",
        vanilla_item="RedAbsorbStone",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 2": WSRLocationData(
        code=200142,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem",
        vanilla_item="Book_Level_Thunder",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 3": WSRLocationData(
        code=200143,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem (1)",
        vanilla_item="AgtStimulus",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 4": WSRLocationData(
        code=200144,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem",
        vanilla_item="ShieldStone",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 5": WSRLocationData(
        code=200145,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem (3)",
        vanilla_item="ShieldStone",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 6": WSRLocationData(
        code=200146,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem (4)",
        vanilla_item="LeafBall",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Arua Temple - Chest 7": WSRLocationData(
        code=200147,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Arua",
        game_id="ChestItem (2)",
        vanilla_item="GuardianPendant",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "South Island - Big Crab Island - Chest": WSRLocationData(
        code=200148,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.CHEST,
        scene="Island_Arua_2",
        game_id="ChestItem (1)",
        vanilla_item="WindBangle",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Durok Temple - Sliding Puzzle - Far Right Chest": WSRLocationData(
        code=200149,
        region=WSRRegionName.DUROK_TEMPLE,
        group=LocationGroup.CHEST,
        scene="Temple_Durok_2",
        game_id="ChestItem (1)",
        vanilla_item="GravityStone",
        vanilla_quantity=5,
        repeat_behavior="none",
    ),
    "Tutorial Ambush - Item 1": WSRLocationData(
        code=200150,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Forest_BlackWitch",
        game_id="event_9",
        method_index=37,
        vanilla_item="DryBread",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Tutorial Ambush - Item 2": WSRLocationData(
        code=200151,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Forest_BlackWitch",
        game_id="event_9",
        method_index=41,
        vanilla_item="DryBread",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),    
    "Tutorial Ambush - Item 3": WSRLocationData(
        code=200152,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Forest_BlackWitch",
        game_id="event_9",
        method_index=45,
        vanilla_item="DryBread",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    #"Event_14 - Mind Control Slab": WSRLocationData(
    #    code=200153,
    #    region=WSRRegionName.PUDDING_CAVE_2,
    #    group=LocationGroup.EVENT,
    #    scene="Cave_Pudding_2",
    #    game_id="event_14",
    #    method_index=138,
    #    vanilla_item="MAGICCIRCLE_MindControl",
    #    vanilla_quantity=1,
    #    repeat_behavior="none",
    #),
    "event_78 - Fire Spellbook": WSRLocationData(
        code=200154,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="#Home_Pieberry",
        game_id="event_78",
        method_index=25,
        vanilla_item="Book_Level_Fire",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Arua Temple Chest - Thunder Slab": WSRLocationData(
        code=200155,
        region=WSRRegionName.ARUA_TEMPLE,
        group=LocationGroup.EVENT,
        scene="Temple_Arua",
        game_id="event_214",
        method_index=11,
        vanilla_item="MAGICCIRCLE_Thunder_3",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    # Ch1 Arua's Arrow blessing - granted at the Black Witch Forest battle after the Arua
    # Temple / Aslan sequence (event_84 m14). Gated on Lightning Magic Spellbook, which is
    # granted in Arua Temple before that fight, so it can't be reached out of order.
    "Arua Blessing": WSRLocationData(
        code=200156,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.BLESSING,
        scene="Forest_BlackWitch",
        game_id="event_84",
        method_index=14,
        vanilla_item="Bless_Arua",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Black Witch Forest - Item 1": WSRLocationData(
        code=200157,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_BlackWitch",
        game_id="Item_DryLeaf_3 (1)",
        vanilla_item="DryLeaf",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),
    "Black Witch Forest - Item 2": WSRLocationData(
        code=200158,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_BlackWitch",
        game_id="Item_DryLeaf_0",
        vanilla_item="DryLeaf",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),
    "Black Witch Forest - Item 3": WSRLocationData(
        code=200159,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_BlackWitch",
        game_id="Item_DryLeaf_3",
        vanilla_item="DryLeaf",
        vanilla_quantity=3,
        repeat_behavior="vanilla_after_first",
    ),
    "Black Witch Forest - Item 4": WSRLocationData(
        code=200160,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_BlackWitch",
        game_id="Item_DryLeaf_3 (2)",
        vanilla_item="DryLeaf",
        vanilla_quantity=1,
        repeat_behavior="vanilla_after_first",
    ),
    "Black Witch Forest - Item 5": WSRLocationData(
        code=200161,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_BlackWitch",
        game_id="Item_DryLeaf_3 (3)",
        vanilla_item="DryLeaf",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),
    "Black Witch Forest - Item 6": WSRLocationData(
        code=200162,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.FIELDITEM,
        scene="Forest_BlackWitch",
        game_id="Item_DryLeaf_2",
        vanilla_item="DryLeaf",
        vanilla_quantity=2,
        repeat_behavior="vanilla_after_first",
    ),
    "Boar Plains - Wagon Protection 1": WSRLocationData(
        code=200163,
        region=WSRRegionName.BOAR_PLAIN,
        group=LocationGroup.EVENT,
        scene="Forest_Boar",
        game_id="event_264",
        method_index=61,
        vanilla_item="Shield_Wood",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Boar Plains - Wagon Protection 2": WSRLocationData(
        code=200164,
        region=WSRRegionName.BOAR_PLAIN,
        group=LocationGroup.EVENT,
        scene="Forest_Boar",
        game_id="event_264",
        method_index=62,
        vanilla_item="Shoes_Leather",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Ralph - Boar Captain's Tooth Reward": WSRLocationData(
        code=200173,
        region=WSRRegionName.NORTH_MERCHANT_ROAD,
        group=LocationGroup.EVENT,
        scene="Road_NorthHill",
        game_id="event_92",
        method_index=7,
        vanilla_item="Gold",
        vanilla_quantity=1000,
        repeat_behavior="none",
    ),
    "Alfredo Ch2 - Item 1": WSRLocationData(
        code=200165,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.EVENT,
        scene="Forest_Lalaque",
        game_id="event_96",
        method_index=23,
        vanilla_item="GoodCookie",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Alfredo Ch2 - Item 2": WSRLocationData(
        code=200166,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.EVENT,
        scene="Forest_Lalaque",
        game_id="event_96",
        method_index=25,
        vanilla_item="WarmBread",
        vanilla_quantity=5,
        repeat_behavior="none",
    ),
    "Anna's House - Item 1": WSRLocationData(
        code=200167,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.EVENT,
        scene="House_Anna",
        game_id="event_101",
        method_index=34,
        vanilla_item="AnnaBread",
        vanilla_quantity=3,
        repeat_behavior="none",
    ),
    # THE GAME STILL FREEZES IF YOU DON'T HAVE THE ITEM SO LET'S LEAVE THIS VANILLA FOR NOW
    #"Event 216 - Chaos Stone": WSRLocationData(
    #    code=200168,
    #    region=WSRRegionName.LALAQUE_MINE,
    #    group=LocationGroup.EVENT,
    #    scene="Forest_Lalaque_Maets",
    #    game_id="event_216",
    #    method_index=34,
    #    vanilla_item="ConfuseStone",
    #    vanilla_quantity=1,
    #    repeat_behavior="none",
    #),
    "Anna's House - Chaos Stone Earrings": WSRLocationData(
        code=200169,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.EVENT,
        scene="House_Anna",
        game_id="event_108",
        method_index=23,
        vanilla_item="OrangeConfusingStone",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Anna's House - Lalaque Mine Key": WSRLocationData(
        code=200170,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.EVENT,
        scene="House_Anna",
        game_id="event_217",
        method_index=98,
        vanilla_item="Key_MineUnderDarkStone",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    # I WOULD LIKE TO ADD THIS AS A CHECK, BUT REQUIRES TESTING TO MAKE SURE IT DOESNT HARDLOCK
    # "Event 139 - Sera Dress": WSRLocationData(
    #    code=200170,
    #    region=WSRRegionName.LALAQUE_FOREST,
    #    group=LocationGroup.EVENT,
    #    scene="Forest_LalaqueEastSouth",
    #    game_id="event_139",
    #    method_index=98,
    #    vanilla_item="SeraDressLaquePeach",
    #    vanilla_quantity=1,
    #    repeat_behavior="none",
    #),
    "Event 453 - Shipwreck Brig Key": WSRLocationData(
        code=200172,
        region=WSRRegionName.LALAQUE_VILLAGE,
        group=LocationGroup.EVENT,
        scene="Village_Lalaque",
        game_id="event_453",
        method_index=73,
        vanilla_item="Key_ShipPrison",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Pudding Cave - Alfredo's Mind Control Circle": WSRLocationData(
        code=200174,
        region=WSRRegionName.PUDDING_CAVE,
        group=LocationGroup.EVENT,
        scene="Cave_Pudding",
        game_id="event_14",
        method_index=138,
        vanilla_item="MAGICCIRCLE_MindControl",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Death Squad - Ice Witch Scarf": WSRLocationData(
        code=200175,
        region=WSRRegionName.DEATH_SQUAD,
        group=LocationGroup.EVENT,
        scene="Cave_BoarMountain",
        game_id="event_308",
        method_index=121,
        vanilla_item="IceScarf",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Shipwreck - Hold Key": WSRLocationData(
        code=200176,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.EVENT,
        scene="ShipWrecked_Enter",
        game_id="event_154",
        method_index=33,
        vanilla_item="Key_ShipStoreKey",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Death Squad - Matt's Letter": WSRLocationData(
        code=200177,
        region=WSRRegionName.DEATH_SQUAD,
        group=LocationGroup.EVENT,
        scene="Cave_BoarMountain",
        game_id="event_340",
        method_index=38,
        vanilla_item="GolemBlueprintInfo",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Death Squad - Secret Trader Key": WSRLocationData(
        code=200178,
        region=WSRRegionName.DEATH_SQUAD,
        group=LocationGroup.EVENT,
        scene="Cave_BoarMountain",
        game_id="event_282",
        method_index=72,
        vanilla_item="Key_RedBeard",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    # Non-blocking check (BlockVanilla=false in Data.cs): the player keeps the vanilla
    # Red Gem to hand to RedBeard later, but picking it up still sends a multiworld check.
    # Ralph hands it over in a cutscene at Kanna's House (he briefly relocates there).
    "Kanna's House - Red Gem": WSRLocationData(
        code=200179,
        region=WSRRegionName.KANNA_HOUSE,
        group=LocationGroup.EVENT,
        scene="House_Canna",
        game_id="event_274",
        method_index=186,
        vanilla_item="RedJewel",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=5,
    ),
    "Reached Chapter 2": WSRLocationData(
        code=201002,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 2",
    ),
    "Reached Chapter 3": WSRLocationData(
        code=201003,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 3",
    ),
    "Reached Chapter 4": WSRLocationData(
        code=201004,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 4",
    ),
    "Reached Chapter 5": WSRLocationData(
        code=201005,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 5",
    ),
    "Reached Chapter 6": WSRLocationData(
        code=201006,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 6",
    ),
    "Reached Chapter 7": WSRLocationData(
        code=201007,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 7",
    ),
    # Chapter 8 doesn't exist in WitchSpring R (7 -> 9); no such "Reached Chapter 8".
    #"Reached Chapter 8": WSRLocationData(
    #    code=201008,
    #    region=WSRRegionName.HOME,
    #    group=LocationGroup.EVENT,
    #    scene="Home",
    #    game_id="Chapter 8",
    #),
    "Reached Chapter 9": WSRLocationData(
        code=201009,
        region=WSRRegionName.HOME,
        group=LocationGroup.EVENT,
        scene="Home",
        game_id="Chapter 9",
    ),
    "Boar Captain Defeated": WSRLocationData(
        code=200500,
        region=WSRRegionName.BOAR_PLAIN,
        group=LocationGroup.EVENT,
        scene="Forest_Boar",
        game_id="BossBoar",
        vanilla_item="BoarBossTooth",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),
    "Shipwreck - Armory - Commander's Cabin Key": WSRLocationData(
        code=200501,
        region=WSRRegionName.SHIPWRECK,
        group=LocationGroup.EVENT,
        scene="ShipWrecked_Cannon",
        game_id="ShipwreckArmoryEnemies",
        vanilla_item="Key_WreckedCaptainRoom",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    # ----- Event-reward checks generated from the Chapter triage worksheet -----
    # (build_event_checks.py, INCLUDE=Y batch). See Events Full Dump/out/REPORT.txt.
    "Red Beard – Frozen Key": WSRLocationData(
        code=201010,
        region=WSRRegionName.REDBEARD_CAVE,
        group=LocationGroup.EVENT,
        scene="Cave_RedBeard_New",
        game_id="event_640",
        method_index=184,
        vanilla_item="Key_Ice",
        vanilla_quantity=1,
        repeat_behavior="none",
    ),

    "Luna – Blue Moonstone Staff": WSRLocationData(
        code=201011,
        region=WSRRegionName.LUNA_HOUSE,
        group=LocationGroup.EVENT,
        scene="House_Luna_New",
        game_id="event_649",
        method_index=5,
        vanilla_item="BlueMoonStick",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=7,
    ),

    "Ludina Blade": WSRLocationData(
        code=201012,
        region=WSRRegionName.FROZEN_ALTAR,
        group=LocationGroup.EVENT,
        scene="SnowLand_Cave2_New",
        game_id="event_654",
        method_index=80,
        vanilla_item="Sword_Ice2",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=6,
    ),

    "Melina – Bedo's Headband": WSRLocationData(
        code=201013,
        region=WSRRegionName.VAVELIA_VILLAGE,
        group=LocationGroup.EVENT,
        scene="Cave_UnderTemple_Jude",
        game_id="event_616",
        method_index=46,
        vanilla_item="BedosHeadband",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=6,
        excluded=True,
    ),

    "Luna – Ice Magic Spellbook": WSRLocationData(
        code=201014,
        region=WSRRegionName.SNOW_FIELD,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_325",
        method_index=48,
        vanilla_item="Book_Level_Ice",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=6,
    ),

    "Balt – Life Stone": WSRLocationData(
        code=201015,
        region=WSRRegionName.ELYSION_PLAIN,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_456",
        method_index=27,
        vanilla_item="LifeStone",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=5,
    ),

    "Royal Pudding Party 1": WSRLocationData(
        code=201016,
        region=WSRRegionName.PUDDING_CAVE_3,
        group=LocationGroup.EVENT,
        scene="Prologue",
        game_id="event_398",
        method_index=32,
        vanilla_item="KingPudding",
        vanilla_quantity=2,
        repeat_behavior="none",
        min_chapter=4,
    ),

    "Royal Pudding Party 2": WSRLocationData(
        code=201017,
        region=WSRRegionName.PUDDING_CAVE_3,
        group=LocationGroup.EVENT,
        scene="Prologue",
        game_id="event_398",
        method_index=33,
        vanilla_item="QueenPudding",
        vanilla_quantity=2,
        repeat_behavior="none",
        min_chapter=4,
    ),

    "Blast – Sun Sword": WSRLocationData(
        code=201018,
        region=WSRRegionName.BLACKHILL_GOLEM_CAVE_FIRE_3,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_397",
        method_index=22,
        vanilla_item="Sword_Fire",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=6,
    ),

    "Kanna – Peanut Shark": WSRLocationData(
        code=201019,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_254",
        method_index=78,
        vanilla_item="BirdSharkSign",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=3,
    ),

    "Livya – Commander's Insignia": WSRLocationData(
        code=201020,
        region=WSRRegionName.SOUTH_ISLAND,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_153",
        method_index=79,
        vanilla_item="LivyaMark",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=3,
    ),

    "Sarah – Sera's Dress": WSRLocationData(
        code=201021,
        region=WSRRegionName.LALAQUE_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_280",
        method_index=12,
        vanilla_item="SeraDressLakeSky",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=2,
    ),

    "Ralph – Gem Payment": WSRLocationData(
        code=201022,
        region=WSRRegionName.NORTH_MERCHANT_ROAD,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_85",
        method_index=32,
        vanilla_item="Gold",
        vanilla_quantity=5000,
        repeat_behavior="none",
        min_chapter=2,
    ),

    "Kanna's House – Chaos Stone": WSRLocationData(
        code=201023,
        region=WSRRegionName.KANNA_HOUSE,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry_New",
        game_id="event_216",
        method_index=34,
        vanilla_item="ConfuseStone",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=2,
    ),

    "Ralph - Boar Captain's Tooth Reward 2": WSRLocationData(
        code=201024,
        region=WSRRegionName.NORTH_MERCHANT_ROAD,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_92",
        method_index=17,
        vanilla_item="CreichLeaf",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=2,
    ),

    "Weapon Upgrade Materials 1": WSRLocationData(
        code=201025,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_80",
        method_index=6,
        vanilla_item="Leaf_MiniGolem",
        vanilla_quantity=12,
        repeat_behavior="none",
    ),

    "Weapon Upgrade Materials 2": WSRLocationData(
        code=201026,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_80",
        method_index=7,
        vanilla_item="DryLeaf",
        vanilla_quantity=12,
        repeat_behavior="none",
    ),

    "Weapon Upgrade Materials 3": WSRLocationData(
        code=201027,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_81",
        method_index=3,
        vanilla_item="DryBread",
        vanilla_quantity=5,
        repeat_behavior="none",
    ),

    "Weapon Upgrade Materials 4": WSRLocationData(
        code=201028,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_81",
        method_index=5,
        vanilla_item="Item_LeafPudding",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    "Weapon Upgrade Materials 5": WSRLocationData(
        code=201029,
        region=WSRRegionName.BLACK_WITCH_FOREST,
        group=LocationGroup.EVENT,
        scene="Home_Pieberry",
        game_id="event_81",
        method_index=7,
        vanilla_item="IronPart",
        vanilla_quantity=2,
        repeat_behavior="none",
    ),

    # ----- Blessing checks (NewBless events; fired by the EventOperator.DoEvent hook) -----
    # Vanilla blessing is kept for now (BlockVanilla=false in Data.cs BlessRewardChecks).
    "Aimhard's Blessing": WSRLocationData(
        code=201030,
        region=WSRRegionName.AIMHARD_TEMPLE,
        group=LocationGroup.BLESSING,
        scene="Temple_Aimhard_Spring",
        game_id="event_178",
        method_index=96,
        vanilla_item="Bless_Aimhard",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=3,
    ),

    "Elysion Blessing": WSRLocationData(
        code=201031,
        region=WSRRegionName.ELYSION_TEMPLE,
        group=LocationGroup.BLESSING,
        scene="Temple_Elicion_Spring",
        game_id="event_200",
        method_index=260,
        vanilla_item="Bless_Elicion",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=4,
    ),

    # Reaching Durok Temple already requires Ice Magic Spellbook + Ch6 + Ice Witch Scarf
    # via the region entrances, so no extra location rule is needed beyond min_chapter.
    "Durok's Blessing": WSRLocationData(
        code=201032,
        region=WSRRegionName.DUROK_TEMPLE,
        group=LocationGroup.BLESSING,
        scene="Temple_Durok",
        game_id="event_334",
        method_index=25,
        vanilla_item="Bless_Durok",
        vanilla_quantity=1,
        repeat_behavior="none",
        min_chapter=6,
    ),
}

location_name_to_id = {
    name: data.code
    for name, data in location_table.items()
}

def location_game_key(data: WSRLocationData) -> str:
    if data.method_index is not None:
        return f"{data.scene}::{data.game_id}::{data.method_index}"
    return f"{data.scene}::{data.game_id}"

def get_location_names_with_ids(location_names: list[str]) -> dict[str, int | None]:
    return {location_name: location_name_to_id[location_name] for location_name in location_names}

#def create_all_locations(world: WSRWorld) -> None:
#    create_regular_locations(world)
#    create_events(world)


