from typing import TYPE_CHECKING
#from rule_builder.rules import Has, HasAll, HasAny, Rule
from BaseClasses import CollectionState
import dataclasses

from worlds.generic.Rules import set_rule
from .items import item_table
from .locations import location_table

if TYPE_CHECKING:
    from .world import WSRWorld

#HAS_FIRE_SPELLBOOK = Has("Fire Magic Spellbook")
#HAS_LIGHTNING_SPELLBOOK = Has("Lightning Magic Spellbook")
#HAS_ICE_SPELLBOOK = Has("Ice Magic Spellbook")
#HAS_MIND_CONTROL = Has("Mind Control Circle")
#HAS_THUNDER_SLAB = Has("3-Fork Lightning Circle")
#HAS_INSIGNIA = Has("Commander's Insignia")

def has(world, item_name: str):
    return lambda state: state.has(item_name, world.player)

def safe_set_location_rule(world, location_name: str, rule):
    try:
        set_rule(world.get_location(location_name), rule)
    except KeyError:
        pass

def safe_set_entrance_rule(world, entrance_name: str, rule):
    try:
        set_rule(world.get_entrance(entrance_name), rule)
    except KeyError:
        pass

def set_all_rules(world) -> None:
    set_location_rules(world)
    set_completion_condition(world)

def set_location_rules(world) -> None:

    # "Arua Blessing" is the Ch1 Arua's Arrow (Bless_Arua, event_84) - granted at a Black
    # Witch Forest battle after the Arua Temple sequence. The Lightning Magic Spellbook is
    # granted in Arua Temple before that fight. Playtesting showed the battle isn't actually
    # reachable until you can progress out of the starting area, so we also require the Fire
    # Magic Spellbook and Mind Control Circle (the Chapter 2 progression pair).
    safe_set_location_rule(world, "Arua Blessing", lambda state: state.has("Lightning Magic Spellbook", world.player) and state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    # Finishing Chapter 1 requires crossing the Swamp/South Island, which needs the Mind
    # Control Circle - so reaching Chapter 2 depends on MCC, not just the Fire Spellbook.
    # Without this, the fill can stash MCC in a Chapter 2+ location (it landed in Lalaque
    # Mine once), which is unreachable until after the point you actually need it.
    safe_set_location_rule(world, "Reached Chapter 2", lambda state: state.has("Fire Magic Spellbook", world.player) and state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Ralph - Boar Captain's Tooth Reward", has(world, "Boar Captain's Tooth"))
    safe_set_location_rule(world, "Anna's House - Chaos Stone Earrings", has(world, "Chaos Stone"))
    safe_set_location_rule(world, "Anna's House - Lalaque Mine Key", has(world, "Chaos Stone"))
    # Reaching Chapter 3 means completing the Lalaque Mine, which is only reachable through
    # Lalaque Forest (needs Boar Captain's Tooth). Without the Tooth requirement the fill can
    # mark Chapter 3 reachable as soon as it hands you the Mine Key - before you can enter the
    # Lalaque area at all (which is why the tracker showed Reached Chapter 3 but no mine checks).
    safe_set_location_rule(world, "Reached Chapter 3", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Lalaque Mine Key", world.player))
    # Chapter 3 main story (in order): Shipwreck then Aimhard. The Rusty Commander's Cabin
    # Key opens the Shipwreck boss; beating it continues the story to Aimhard / Chapter 4.
    # (Cannonball is NOT in this chain - it only opens the Armory loot.)
    safe_set_location_rule(world, "Reached Chapter 4", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Reached Chapter 5", has(world, "Chapter 4"))
    # Reaching Chapter 6 requires the Prototype Steam Engine (story-critical to trigger the
    # transition), so the fill can't stash it in a Chapter 6+ location.
    safe_set_location_rule(world, "Reached Chapter 6", lambda state: state.has("Chapter 5", world.player) and state.has("Prototype Steam Engine", world.player))
    safe_set_location_rule(world, "Reached Chapter 7", has(world, "Chapter 6"))
    # Chapter 8 doesn't exist in-game (7 -> 9), so Chapter 9 follows directly from 7.
    safe_set_location_rule(world, "Reached Chapter 9", has(world, "Chapter 7"))
    # Shipwreck interior chests are locked behind their keys.
    safe_set_location_rule(world, "Shipwreck - Brig - Chest 1", has(world, "Shipwreck Brig Key"))
    safe_set_location_rule(world, "Shipwreck - Brig - Chest 2", has(world, "Shipwreck Brig Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 1", has(world, "Shipwreck Hold Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 2", has(world, "Shipwreck Hold Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 3", has(world, "Shipwreck Hold Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 4", has(world, "Shipwreck Hold Key"))
    # The Cabin Key drops from the Armory enemy fight, so it also sits behind the Hold Key.
    safe_set_location_rule(world, "Shipwreck - Armory - Commander's Cabin Key", has(world, "Shipwreck Hold Key"))
    # The Red Gem cutscene happens at Kanna's House (reachable from Ch2 Lalaque Forest) but
    # only fires in Chapter 5, so gate the check on Chapter 5 even though the region is earlier.
    safe_set_location_rule(world, "Kanna's House - Red Gem", has(world, "Chapter 5"))
    # The Fire Spellbook is handed over only after the Mind-Control swamp sequence in-game,
    # so this location can't be checked until the player has the Mind Control Circle.
    safe_set_location_rule(world, "event_78 - Fire Spellbook", has(world, "Mind Control Circle"))
    # Boar_Junior (the Mind Control Circle, gated in-game on event_13) is required to
    # reach the Swamp, and to ride through it to BlackJoe and on to South Island.
    safe_set_entrance_rule(world, "Black Witch Forest to Swamp", has(world, "Mind Control Circle"))
    # South Island is reached by riding through the swamp past Black Joe, who hands over the
    # Fire Magic Spellbook - so you must already have it (plus MCC) to get there. Without
    # this, the fill could place the Fire Spellbook behind South Island and softlock.
    safe_set_entrance_rule(world, "Black Witch Forest to South Island", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_entrance_rule(world, "South Island to Shipwreck", has(world, "Chapter 3"))
    # South Island - Chest 1 is on a swim-only islet, reached with Eison (the swimming mount,
    # awakened by the Aged Lalaque Berry in Chapter 2). Gate on Chapter 2 + the berry as the
    # swim-pet proxy until pets are in logic. (Big Crab Island chest is reachable on foot.)
    safe_set_location_rule(world, "South Island - Chest 1", lambda state: state.has("Chapter 2", world.player) and state.has("Aged Lalaque Berry", world.player))
    # Lions Plain -> Aimhard Temple is the Chapter 3 branch off Lalaque Forest.
    safe_set_entrance_rule(world, "Lalaque Forest to Lions Plain", has(world, "Chapter 3"))
    # The Shipwreck boss (opened by the Cabin Key) must be beaten to reach Aimhard.
    safe_set_entrance_rule(world, "Lions Plain to Aimhard Temple", has(world, "Rusty Commander's Cabin Key"))
    # Pudding Cave - Royal Pudding is Chapter 4 content off Pudding Cave 2.
    safe_set_entrance_rule(world, "Pudding Cave 2 to Pudding Cave - Royal Pudding", has(world, "Chapter 4"))
    # Elysion Plain -> Darkstone Cave -> Elysion Temple is the Chapter 4 branch off Backhill Golem Cave.
    safe_set_entrance_rule(world, "Backhill Golem Cave to Elysion Plain", has(world, "Chapter 4"))
    # Vavelia Road/Village are Chapter 5 content off Laoba Mountain.
    safe_set_entrance_rule(world, "Laoba Mountain to Vavelia Road", has(world, "Chapter 5"))
    # Death Squad (Boar Mountain lair) is Chapter 5 content off Boar Plain.
    safe_set_entrance_rule(world, "Boar Plain to Death Squad", has(world, "Chapter 5"))
    # RedBeard's Cave (off Vavelia Village) is gated by the Secret Trader Key.
    safe_set_entrance_rule(world, "Vavelia Village to RedBeard's Cave", has(world, "Secret Trader Key"))
    # Snow Field -> Durok Temple is Chapter 6 content off Boar Plain.
    # The Ice Witch Scarf is required to enter Snow Field at all.
    safe_set_entrance_rule(world, "Boar Plain to Snow Field", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    # The Ice Magic Spellbook is needed to get through the Ice Cave, and the same Ice magic
    # gates Durok Temple. (Durok currently hangs off Snow Field, so we require it on both
    # entrances directly; if Durok is ever re-routed through the Ice Cave the Ice Cave gate
    # alone would cover it.)
    safe_set_entrance_rule(world, "Snow Field to Ice Cave", has(world, "Ice Magic Spellbook"))
    safe_set_entrance_rule(world, "Snow Field to Durok Temple", has(world, "Ice Magic Spellbook"))
    # The Laoba Mountain Warrior Camp opens up once you've beaten the Boar Captain (i.e. have
    # the Boar Captain's Tooth), so gate it on the Tooth rather than Chapter 3 - it's reachable
    # in Chapter 2 in practice. (Deeper Laoba->Vavelia content stays gated at Chapter 5 below.)
    safe_set_entrance_rule(world, "Boar Plain to Laoba Mountain", has(world, "Boar Captain's Tooth"))
    # The Fire Cave / Volcano Road branch can't be entered until the Mind Control Circle quest
    # is done (UT-confirmed); this also covers the deeper Volcano Road 2/3 beyond it.
    safe_set_entrance_rule(world, "Backhill Golem Cave to Backhill Golem Cave Volcano Road", has(world, "Mind Control Circle"))
    # Entrance Chest 1 specifically is blocked behind Mind Control (its sibling chests aren't).
    safe_set_location_rule(world, "Backhill Golem Cave - Entrance - Chest 1", has(world, "Mind Control Circle"))
    # Volcano Road 2/3 technically enterable in Ch3 but underleveled - gate the deeper stretch at Ch4.
    safe_set_entrance_rule(world, "Backhill Golem Cave Volcano Road to Backhill Golem Cave Volcano Road 2", has(world, "Chapter 4"))
    safe_set_entrance_rule(world, "Black Witch Forest to North Merchant Road", has(world, "Chapter 2"))
    safe_set_entrance_rule(world, "North Merchant Road to Lalaque Forest", has(world, "Boar Captain's Tooth"))
    # Fox Den chest is accessible from the beginning, but the foxes suck, so let's push it back 2 chapters because why not.
    safe_set_location_rule(world, "Backhill Golem Cave - Fox Den - Chest", has(world, "Chapter 3"))
    # Pudding Cave Deep checks, accessible from the beginning but lets push them to Chapter 2 for more exp gain before the fight
    safe_set_location_rule(world, "Pudding Cave - Deep - Back Left Item", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave - Deep - Top Left Chest", has(world, "Chapter 2"))

    # ----- Event-reward check rules generated from the Chapter triage worksheet -----
    # (build_event_checks.py, INCLUDE=Y batch). See Events Full Dump/out/REPORT.txt.
    safe_set_location_rule(world, "Luna – Blue Moonstone Staff", lambda state: state.has('Chapter 7', world.player))
    safe_set_location_rule(world, "Ludina Blade", lambda state: state.has('Chapter 6', world.player) and state.has('Frozen Key', world.player))
    safe_set_location_rule(world, "Melina – Bedo's Headband", lambda state: state.has('Chapter 6', world.player))
    safe_set_location_rule(world, "Luna – Ice Magic Spellbook", lambda state: state.has('Chapter 6', world.player))
    safe_set_location_rule(world, "Balt – Life Stone", lambda state: state.has('Chapter 5', world.player))
    safe_set_location_rule(world, "Royal Pudding Party 1", lambda state: state.has('Chapter 4', world.player) and state.has('Aged Lalaque Berry', world.player))
    safe_set_location_rule(world, "Royal Pudding Party 2", lambda state: state.has('Chapter 4', world.player) and state.has('Aged Lalaque Berry', world.player))
    safe_set_location_rule(world, "Blast – Sun Sword", lambda state: state.has('Chapter 6', world.player))
    safe_set_location_rule(world, "Kanna – Peanut Shark", lambda state: state.has('Chapter 3', world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Livya – Commander's Insignia", lambda state: state.has('Chapter 3', world.player))
    safe_set_location_rule(world, "Sarah – Sera's Dress", lambda state: state.has('Chapter 2', world.player))
    safe_set_location_rule(world, "Ralph – Gem Payment", lambda state: state.has('Chapter 2', world.player))
    safe_set_location_rule(world, "Kanna's House – Chaos Stone", lambda state: state.has('Chapter 2', world.player))
    safe_set_location_rule(world, "Ralph - Boar Captain's Tooth Reward 2", lambda state: state.has('Chapter 2', world.player))
    # The Weapon Upgrade Materials handout needs both the Fire Magic Spellbook and the Mind
    # Control Circle in-game (UT-confirmed), so require both.
    safe_set_location_rule(world, "Weapon Upgrade Materials 1", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 2", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 3", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 4", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 5", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))

    # Blessing checks (NewBless events).
    safe_set_location_rule(world, "Aimhard's Blessing", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Elysion Blessing", has(world, "Chapter 4"))
    # === BEGIN Battlesanity (generated) ===
    safe_set_location_rule(world, "Arua Temple - Battle 1", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Arua Temple - Battle 2", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Arua Temple - Battle 3", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Arua Temple - Battle 4", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 7", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 8", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 9", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 10", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 11", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 1", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 2", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 3", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 4", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 5", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 6", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 7", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 4", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 5", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 6", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Boar Plain - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Boar Plain - Battle 2", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Boar Plain - Battle 3", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Boar Plain - Battle 4", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Darkstone Cave - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Darkstone Cave - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Darkstone Cave - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 5", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 6", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 7", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 8", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 9", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 10", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Elysion Plain - Battle 11", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 12", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 13", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 14", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 15", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 2", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 3", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 4", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 5", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 6", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 7", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 2", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 3", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 4", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 5", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 6", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 7", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 8", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 9", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 10", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 11", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 12", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 13", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 14", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Laoba Mountain - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Laoba Mountain - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Laoba Mountain - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Pudding Cave 2 - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave 2 - Battle 2", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave - Royal Pudding - Battle 1", has(world, "Aged Lalaque Berry"))
    safe_set_location_rule(world, "Shipwreck - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Shipwreck - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Shipwreck - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Shipwreck - Battle 4", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Shipwreck - Battle 5", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Snow Field - Battle 1", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 2", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 3", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 4", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 5", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 6", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 7", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 8", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 9", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 10", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 11", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 12", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 13", has(world, "Chapter 6"))
    safe_set_location_rule(world, "South Island - Battle 1", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 2", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 3", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 4", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 5", has(world, "Chapter 5"))
    safe_set_location_rule(world, "South Island - Battle 6", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Swamp - Battle 1", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 2", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 3", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 4", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 5", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 6", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 7", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 8", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 9", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Swamp - Battle 10", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Vavelia Road - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Vavelia Road - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 5", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 6", has(world, "Chapter 4"))
    # === END Battlesanity (generated) ===
    # === BEGIN Bestiary (generated) ===
    safe_set_location_rule(world, "Bestiary - Boar Junior", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Junior Plains Boar", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Lalaque Village Warrior", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Wild Dog", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Giant Blue Crab", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Lalaque Village Archer", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Magmata", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Bomb Spider", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Wampleaf", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Grown-up Dwarf Golem", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Rogue Rabbit", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Crow", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Jack-in-the-box", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Tiny Volcanic Golem", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Bandits Captain Kanna", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - White Fox", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Red Hawk", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Steam Launcher", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Tainted Carico", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Mid-Rank Lalaque Warrior", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Stone Fox", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Tiny Demon", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Low-Rank Dark Palace Warrior", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Ugly Bird", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Laquerak", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Leaf Golem", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Carico", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Boar Captain", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Giant Wampleaf", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Defensive Mid-Rank Palace Warrior", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Ugly Birds Captain", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Goat Statue", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Tia Reese", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Tia Reet", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Tia Rion", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Steam Golem 003", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Dark Lion", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - High-Rank Palace Warrior", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Poison Golem", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Lucca", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Buffalo Gorilla", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Tiny Giant", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Steam Golem 002", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - Horned Deer", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Dark Mid-Rank Palace Warrior", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Pudding Queen", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Fire Demon", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Nekomis", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Ancient Lightning Dragon Junior", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Fire Frog", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Royal Palace Special Forces Warrior", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - Big Crab", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Pudding King", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Caric", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Bestiary - White Rhino", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Brillion", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Yeti", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Water Balloon Frog", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Lava", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Dark High-Rank Palace Warrior", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - High-Rank Elite Warrior", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - Zircon Dragon", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Supreme Warrior", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - White Giant", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - Ancient Garden Wampleaf", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Bestiary - Ice Giant", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Old Yeti", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Lightnoceros", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Tainted Darkstone Cave Giant", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Shipwreck Beruch", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Bestiary - Lightning Dragon", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Zirconia Dragon", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - Ancient Lightning Dragon", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Bestiary - Blast", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Bestiary - Narrel", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Bestiary - Temar", has(world, "Chapter 6"))
    # === END Bestiary (generated) ===
    # === BEGIN QuestSanity (generated) ===
    safe_set_location_rule(world, "Quest - Visiting Anna's House", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Temple Trial", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Sneaking Past the Warriors", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Giant Bird", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Searching for the Intruder", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Checking on Anna", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Investigating the Snow Field Entrance", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Returning the Commander's Insignia", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Crown Vs Excuter", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Nuuk Field Outlaw", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Delivering the Chaos Stone to Anna", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Giving Kanna the Engine", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Durok's Spring", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Eternal Ice", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Infiltrating the Pope's Castle", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Quest - Strawberries Hunt in the Boar Plain", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Helping Kanna", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Finding the Children of Lalaque", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Investigating Shipwreck", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Finding Red Beard's Lair", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Listening to Reina", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Saving David", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Going to Durok Temple", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Ready for War", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Quest - Shipwreck  Commander's Cabin", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Exploring Aimhard Temple", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Entering the Snow Field", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Visiting Kanna's House", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Defeating the Ice Giant", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Leaving Matt's Garden", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Finding the Pie Maker!", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Finding Luna's House", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Darkstone Cave", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Return to Ralph!", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - First Trade with Ralph", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Prison Break", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Gorrila Grass", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Finding Sara", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - High Level Armor Ore", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Reporting to Verstein", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Sharing Results with Verstein", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Telling Kanna the News", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Kate And Livya", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Finding the Pie Maker in Lalaque Village", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Tracking the Bomb Witch", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Legend Pudding", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Exorcizing the Evil Demons in the Village", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Collapsed Justice", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Riding a Nuuk", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Connecting the Mine to the House", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Anna's Advice", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Following Alfredo!", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Finding Anna", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Anxious Anna", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Finding the Chaos Stone", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Entrance to Elysion Temple", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Tracking Down Justice", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Finding Kate's Sibling", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Thorough Exorcism", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - To Aimhard Temple", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - To Elysion Temple", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - West of Elysion Plain", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Going to the Snow Field", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Reassuring Anna", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Informing Anna", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Barrier Wall", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Discovered Anna", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Finding Memories", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Leaning Ice Magic", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Narer Ralph", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Quest - New Clothes", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Passing Arua's Test", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Ralph Quest Blue Crab Cover", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Ralph Quest Fire Stone", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Ralph Quest Iron Ore", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Ralph Quest Iron Ore 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Ralph Quest Leaf Mini Golem", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Ralph Quest Pudding", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Ralph Quest Warriors Sword Thunder Material", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Ralph Quest Warriors Sword Thunder Material 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Read Beard Giant Dark Stone", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Power to Protect", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Red Beard Ice Head", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Red Beard Lavastain", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Red Beard Lightning Dragon Horn", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Behind Bars", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Red Beards Package Arrives", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Delivering Strawberries", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Get Some Sleep", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - The War Begins", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Quest - Suspicious Shipwreck Key", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Suspicious Cave", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Exploring the Village", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Suspicious Justice", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Memories of the Past", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Temar's Trial", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Alfredo the Thief", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - To Aramute Spring", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Quest - Discovering Elysion Temple", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Father's Grave", has(world, "Chapter 7"))
    safe_set_location_rule(world, "Quest - Tracking the Bandits", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Waiting for Luna", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - War Horn", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Warrior Magic Weapon", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Quest - Hurried Review", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Exploring Elysion Temple", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Quest - Checking on Justice 2", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Checking on Justice", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Quest - Investigate Lalaque Forest", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Spying on Livya", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Quest - Matt's Garden", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Quest - Exploring the Wreck", has(world, "Chapter 3"))
    # === END QuestSanity (generated) ===
def set_completion_condition(world) -> None:
    goal_choice = int(world.options.goal_choice.value)
    #world.set_completion_rule(HAS_ICE_SPELLBOOK)
    world.multiworld.completion_condition[world.player] = has(world, f"Chapter {goal_choice}")
    #world.multiworld.completion_rule(has(world, "Ice Magic Spellbook"))