from typing import TYPE_CHECKING
#from rule_builder.rules import Has, HasAll, HasAny, Rule
from BaseClasses import CollectionState
import dataclasses

from worlds.generic.Rules import set_rule
from .items import item_table
from .locations import location_table

if TYPE_CHECKING:
    from .world import WSRWorld

#HAS_FIRE_SPELLBOOK = Has("Fire Magic Spellbook")
#HAS_LIGHTNING_SPELLBOOK = Has("Lightning Magic Spellbook")
#HAS_ICE_SPELLBOOK = Has("Ice Magic Spellbook")
#HAS_MIND_CONTROL = Has("Mind Control Circle")
#HAS_THUNDER_SLAB = Has("3-Fork Lightning Circle")
#HAS_INSIGNIA = Has("Commander's Insignia")

def has(world, item_name: str):
    return lambda state: state.has(item_name, world.player)

def safe_set_location_rule(world, location_name: str, rule):
    try:
        set_rule(world.get_location(location_name), rule)
    except KeyError:
        pass

def safe_set_entrance_rule(world, entrance_name: str, rule):
    try:
        set_rule(world.get_entrance(entrance_name), rule)
    except KeyError:
        pass

def set_all_rules(world) -> None:
    set_location_rules(world)
    set_completion_condition(world)

def set_location_rules(world) -> None:

    # "Arua Blessing" is the Ch1 Arua's Arrow (Bless_Arua, event_84) - granted at a Black
    # Witch Forest battle after the Arua Temple sequence. The Lightning Magic Spellbook is
    # granted in Arua Temple before that fight. Playtesting showed the battle isn't actually
    # reachable until you can progress out of the starting area, so we also require the Fire
    # Magic Spellbook and Mind Control Circle (the Chapter 2 progression pair).
    safe_set_location_rule(world, "Arua Blessing", lambda state: state.has("Lightning Magic Spellbook", world.player) and state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    # "Arua Thunder Blessing" (Bless_AruaThunder, event_226) is the Ch3 Arua Statue Trial.
    # Arua Temple is a Chapter-1 region and min_chapter only controls pool inclusion (not
    # reachability), so without this explicit rule it would show in logic from the start.
    safe_set_location_rule(world, "Arua Thunder Blessing", has(world, "Chapter 3"))
    # Finishing Chapter 1 requires crossing the Swamp/South Island, which needs the Mind
    # Control Circle - so reaching Chapter 2 depends on MCC, not just the Fire Spellbook.
    # Without this, the fill can stash MCC in a Chapter 2+ location (it landed in Lalaque
    # Mine once), which is unreachable until after the point you actually need it.
    safe_set_location_rule(world, "Reached Chapter 2", lambda state: state.has("Fire Magic Spellbook", world.player) and state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Ralph - Boar Captain's Tooth Reward", has(world, "Boar Captain's Tooth"))
    safe_set_location_rule(world, "Anna's House - Chaos Stone Earrings", has(world, "Chaos Stone"))
    safe_set_location_rule(world, "Anna's House - Lalaque Mine Key", has(world, "Chaos Stone"))
    # Reaching Chapter 3 means completing the Lalaque Mine, which is only reachable through
    # Lalaque Forest (needs Boar Captain's Tooth). Without the Tooth requirement the fill can
    # mark Chapter 3 reachable as soon as it hands you the Mine Key - before you can enter the
    # Lalaque area at all (which is why the tracker showed Reached Chapter 3 but no mine checks).
    # Chaos Stone added (player report, 2026-07): the Ch2->3 story path runs through the
    # Chaos Stone beats in Lalaque, so Chapter 3 can't happen without it.
    safe_set_location_rule(world, "Reached Chapter 3", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Lalaque Mine Key", world.player) and state.has("Chaos Stone", world.player))
    # Chapter 3 main story (in order): Shipwreck then Aimhard. The Rusty Commander's Cabin
    # Key opens the Shipwreck boss; beating it continues the story to Aimhard / Chapter 4.
    # (Cannonball is NOT in this chain - it only opens the Armory loot.)
    safe_set_location_rule(world, "Reached Chapter 4", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    # Matt's Garden Passage Key is handed over in the Under Lalaque cave after the Chaos Stone
    # delivery (Canna/Redhawk crisis). It opens the iron gate to Canna's house -> Aimhard -> Ch4.
    safe_set_location_rule(world, "Matt's Garden Passage Key", lambda state: state.has("Chapter 3", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Reached Chapter 5", has(world, "Chapter 4"))
    # Reaching Chapter 6 requires the Prototype Steam Engine (story-critical to trigger the
    # transition), so the fill can't stash it in a Chapter 6+ location.
    safe_set_location_rule(world, "Reached Chapter 6", lambda state: state.has("Chapter 5", world.player) and state.has("Prototype Steam Engine", world.player))
    safe_set_location_rule(world, "Reached Chapter 7", has(world, "Chapter 6"))
    # Chapter 8 doesn't exist in-game (7 -> 9), so Chapter 9 follows directly from 7.
    safe_set_location_rule(world, "Reached Chapter 9", has(world, "Chapter 7"))
    # Shipwreck interior chests are locked behind their keys.
    safe_set_location_rule(world, "Shipwreck - Brig - Chest 1", lambda state: state.has("Shipwreck Brig Key", world.player) and state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Shipwreck - Brig - Chest 2", has(world, "Shipwreck Brig Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 1", has(world, "Shipwreck Hold Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 2", has(world, "Shipwreck Hold Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 3", has(world, "Shipwreck Hold Key"))
    safe_set_location_rule(world, "Shipwreck - Armory - Chest 4", has(world, "Shipwreck Hold Key"))
    # The Cabin Key drops from the Armory enemy fight, so it also sits behind the Hold Key.
    safe_set_location_rule(world, "Shipwreck - Armory - Commander's Cabin Key", has(world, "Shipwreck Hold Key"))
    # The Red Gem cutscene happens at Kanna's House (reachable from Ch2 Lalaque Forest) but
    # only fires in Chapter 5, so gate the check on Chapter 5 even though the region is earlier.
    safe_set_location_rule(world, "Kanna's House - Red Gem", has(world, "Chapter 5"))
    # The Fire Spellbook is handed over only after the Mind-Control swamp sequence in-game,
    # so this location can't be checked until the player has the Mind Control Circle.
    safe_set_location_rule(world, "event_78 - Fire Spellbook", has(world, "Mind Control Circle"))
    # Boar_Junior (the Mind Control Circle, gated in-game on event_13) is required to
    # reach the Swamp, and to ride through it to BlackJoe and on to South Island.
    safe_set_entrance_rule(world, "Black Witch Forest to Swamp", has(world, "Mind Control Circle"))
    # South Island is reached by riding through the swamp past Black Joe, who hands over the
    # Fire Magic Spellbook - so you must already have it (plus MCC) to get there. Without
    # this, the fill could place the Fire Spellbook behind South Island and softlock.
    safe_set_entrance_rule(world, "Black Witch Forest to South Island", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_entrance_rule(world, "South Island to Shipwreck", has(world, "Chapter 3"))
    # --- Ch1+2 playthrough logic fixes (field-item / event / NPC-reward checks) ---
    safe_set_location_rule(world, "Lalaque Village - Farm 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lalaque Village - Farm 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lalaque Village - Farm 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lalaque Village - Anna's House", has(world, "Chaos Stone"))
    # Big Crab Island chest is in South Island (already behind MCC+Fire via the region); held
    # to Chapter 2 so players get some buffer before it's expected in logic.
    safe_set_location_rule(world, "South Island - Big Crab Island - Chest", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Event 453 - Shipwreck Brig Key", lambda state: state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player) and state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Sarah – Sera's Dress", lambda state: state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player) and state.has("Chapter 5", world.player))
    # South Island - Chest 1 re-added as "South Island - Behind Temple" (found behind the
    # temple); gated by Mind Control Circle + Fire Magic Spellbook via the South Island region.
    # --- Ch3 playthrough logic fixes ---
    # Aimhard Temple prison chests live in the Aimhard region (reached with the Rusty
    # Commander's Cabin Key in Ch3), same gate as Aimhard's Blessing.
    safe_set_location_rule(world, "Aimhard Temple - Prison - Chest 1", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    # (Prison Chest 2 & 3 removed from the pool - couldn't be found, assumed NG+ for now.)
    safe_set_location_rule(world, "Aimhard Temple - Prison - Chest 4", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    # Key inside Lions Plain (circular lock). Gating the entrance covers all Lions Plain
    # content + Aimhard transitively.
    safe_set_entrance_rule(world, "Lalaque Forest to Lions Plain", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    # Aimhard additionally needs Matt's Garden Passage Key (Cabin Key already covered by
    # the Lions Plain entrance above, kept here for clarity).
    safe_set_entrance_rule(world, "Lions Plain to Aimhard Temple", lambda state: state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    # Pudding Cave - Royal Pudding is behind the "To Elysion Temple" quest (modeled Ch5).
    safe_set_entrance_rule(world, "Pudding Cave 2 to Pudding Cave - Royal Pudding", has(world, "Chapter 5"))
    # Elysion Plain -> Darkstone Cave -> Elysion Temple is the Chapter 4 branch off Backhill Golem Cave.
    safe_set_entrance_rule(world, "Backhill Golem Cave to Elysion Plain", has(world, "Chapter 4"))
    # The Elysion Plain boulder (cleared by Narrel, event_190) blocks the path deeper; gate
    # Darkstone Cave + Elysion Temple behind the synthetic "Narrel" item (matching SwitchGate).
    safe_set_entrance_rule(world, "Elysion Plain to Darkstone Cave", has(world, "Narrel"))
    # Vavelia Road/Village are Chapter 5 content off Laoba Mountain.
    safe_set_entrance_rule(world, "Laoba Mountain to Vavelia Road", has(world, "Chapter 5"))
    # Death Squad (Boar Mountain lair) is Chapter 5 content off Boar Plain.
    safe_set_entrance_rule(world, "Boar Plain to Death Squad", has(world, "Chapter 5"))
    # RedBeard's Cave (off Vavelia Village) is gated by the Secret Trader Key.
    safe_set_entrance_rule(world, "Vavelia Village to RedBeard's Cave", has(world, "Secret Trader Key"))
    # Snow Field -> Durok Temple is Chapter 6 content off Boar Plain.
    # The Ice Witch Scarf is required to enter Snow Field at all.
    safe_set_entrance_rule(world, "Boar Plain to Snow Field", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    # The Ice Magic Spellbook is needed to get through the Ice Cave, and the same Ice magic
    # gates Durok Temple. (Durok currently hangs off Snow Field, so we require it on both
    # entrances directly; if Durok is ever re-routed through the Ice Cave the Ice Cave gate
    # alone would cover it.)
    safe_set_entrance_rule(world, "Snow Field to Ice Cave", has(world, "Ice Magic Spellbook"))
    safe_set_entrance_rule(world, "Snow Field to Durok Temple", has(world, "Ice Magic Spellbook"))
    # The Laoba Mountain Warrior Camp physically opens with the Boar Captain's Tooth, but
    # players reported it's brutally hard at that power level - so logic also expects the
    # Chaos Stone (the mid-Chapter-2 milestone), landing it in the second half of Ch2.
    # Gates ALL Laoba checks transitively via the entrance; the three battles keep their
    # stricter individual Chapter 3 rules. (Deeper Laoba->Vavelia stays Chapter 5 below.)
    safe_set_entrance_rule(world, "Boar Plain to Laoba Mountain", lambda state: state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player))
    # The Fire Cave / Volcano Road branch can't be entered until the Mind Control Circle quest
    # is done (UT-confirmed); this also covers the deeper Volcano Road 2/3 beyond it.
    safe_set_entrance_rule(world, "Backhill Golem Cave to Backhill Golem Cave Volcano Road", has(world, "Mind Control Circle"))
    # Entrance Chest 1 specifically is blocked behind Mind Control (its sibling chests aren't).
    safe_set_location_rule(world, "Backhill Golem Cave - Entrance - Chest 1", has(world, "Mind Control Circle"))
    # Volcano Road 2 technically enterable in Ch3 but underleveled - gate at Ch4. Volcano Road 3
    # sits behind the "To Elysion Temple" quest (tough enemies) - modeled as Chapter 5.
    safe_set_entrance_rule(world, "Backhill Golem Cave Volcano Road to Backhill Golem Cave Volcano Road 2", has(world, "Chapter 4"))
    safe_set_entrance_rule(world, "Backhill Golem Cave Volcano Road 2 to Backhill Golem Cave Volcano Road 3", has(world, "Chapter 5"))
    safe_set_entrance_rule(world, "Black Witch Forest to North Merchant Road", has(world, "Chapter 2"))
    safe_set_entrance_rule(world, "North Merchant Road to Lalaque Forest", has(world, "Boar Captain's Tooth"))
    # Fox Den chest is accessible from the beginning, but the foxes suck, so let's push it back 2 chapters because why not.
    safe_set_location_rule(world, "Backhill Golem Cave - Fox Den - Chest", has(world, "Chapter 3"))
    # Pudding Cave Deep checks, accessible from the beginning but lets push them to Chapter 2 for more exp gain before the fight
    safe_set_location_rule(world, "Pudding Cave - Deep - Back Left Item", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave - Deep - Top Left Chest", has(world, "Chapter 2"))

    # --- Ch5 playthrough logic fixes ---
    # The Great Key (Vavelia "Ground by Bridge", now an AP item) opens these two chests.
    safe_set_location_rule(world, "Vavelia Village - Houses - Chest 4", has(world, "Great Key"))
    safe_set_location_rule(world, "Vavelia Village - Houses - Chest 5", has(world, "Great Key"))
    # Red Beard - Frozen Key (event check) and the Red Beard questline are behind RedBeard's
    # Cave, which the Secret Trader Key opens.
    safe_set_location_rule(world, "Red Beard – Frozen Key", has(world, "Secret Trader Key"))

    # ----- Event-reward check rules generated from the Chapter triage worksheet -----
    # (build_event_checks.py, INCLUDE=Y batch). See Events Full Dump/out/REPORT.txt.
    safe_set_location_rule(world, "Luna – Blue Moonstone Staff", lambda state: state.has('Chapter 7', world.player))
    safe_set_location_rule(world, "Ludina Blade", lambda state: state.has('Chapter 6', world.player) and state.has('Frozen Key', world.player))
    safe_set_location_rule(world, "Melina – Bedo's Headband", lambda state: state.has('Chapter 6', world.player))
    safe_set_location_rule(world, "Luna – Ice Magic Spellbook", lambda state: state.has('Chapter 6', world.player))
    safe_set_location_rule(world, "Balt – Life Stone", lambda state: state.has('Chapter 5', world.player))
    safe_set_location_rule(world, "Royal Pudding Party 1", lambda state: state.has('Chapter 4', world.player) and state.has('Aged Lalaque Berry', world.player))
    safe_set_location_rule(world, "Royal Pudding Party 2", lambda state: state.has('Chapter 4', world.player) and state.has('Aged Lalaque Berry', world.player))
    safe_set_location_rule(world, "Blast – Sun Sword", lambda state: state.has('Chapter 6', world.player))
    safe_set_location_rule(world, "Kanna – Peanut Shark", lambda state: state.has('Chapter 3', world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Livya – Commander's Insignia", lambda state: state.has('Chapter 3', world.player))
    safe_set_location_rule(world, "Ralph – Gem Payment", lambda state: state.has('Chapter 2', world.player))
    safe_set_location_rule(world, "Kanna's House – Chaos Stone", lambda state: state.has('Chapter 2', world.player))
    safe_set_location_rule(world, "Ralph - Boar Captain's Tooth Reward 2", lambda state: state.has('Chapter 2', world.player))
    # The Weapon Upgrade Materials handout needs both the Fire Magic Spellbook and the Mind
    # Control Circle in-game (UT-confirmed), so require both.
    safe_set_location_rule(world, "Weapon Upgrade Materials 1", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 2", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 3", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 4", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))
    safe_set_location_rule(world, "Weapon Upgrade Materials 5", lambda state: state.has('Fire Magic Spellbook', world.player) and state.has('Mind Control Circle', world.player))

    # Blessing checks (NewBless events).
    safe_set_location_rule(world, "Aimhard's Blessing", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Elysion Blessing", has(world, "Chapter 4"))
    # === BEGIN Battlesanity (generated) ===
    safe_set_location_rule(world, "Arua Temple - Battle 1", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Arua Temple - Battle 2", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Arua Temple - Battle 3", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Arua Temple - Battle 4", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Arua Temple - Battle 5", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Arua Temple - Battle 6", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Arua Temple - Battle 7", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 5", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 6", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 7", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 8", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 9", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 10", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 11", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 12", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Backhill Golem Cave - Battle 13", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 1", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 2", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 4", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 5", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 6", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road - Battle 7", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 2 - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Volcano Road 3 - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 4", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 5", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Backhill Golem Cave Fox - Battle 6", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Black Witch Forest - Battle 3", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Black Witch Forest - Battle 4", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Black Witch Forest - Battle 5", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Black Witch Forest - Battle 6", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Black Witch Forest - Battle 7", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Black Witch Forest - Battle 8", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Black Witch Forest - Battle 9", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Boar Plain - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Boar Plain - Battle 4", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Boar Plain - Battle 5", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Boar Plain - Battle 7", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Boar Plain - Battle 8", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Darkstone Cave - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Darkstone Cave - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Darkstone Cave - Battle 4", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Death Squad - Battle 2", has(world, "Prototype Steam Engine"))
    safe_set_location_rule(world, "Death Squad - Battle 3", has(world, "Prototype Steam Engine"))
    safe_set_location_rule(world, "Death Squad - Battle 4", has(world, "Prototype Steam Engine"))
    safe_set_location_rule(world, "Death Squad - Battle 5", has(world, "Prototype Steam Engine"))
    safe_set_location_rule(world, "Elysion Plain - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 5", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 6", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 7", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 8", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 9", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 10", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 11", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 12", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 13", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 14", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Elysion Plain - Battle 15", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Elysion Plain - Battle 16", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Elysion Plain - Battle 17", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 2", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 3", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 5", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 6", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 7", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Lalaque Forest - Battle 8", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Lalaque Forest - Battle 9", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 10", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Lalaque Forest - Battle 11", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Lalaque Forest - Battle 12", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Lalaque Forest - Battle 13", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Lalaque Forest - Battle 14", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Lalaque Forest - Battle 15", lambda state: state.has("Chapter 6", world.player) and state.has("Soul Sword", world.player))
    safe_set_location_rule(world, "Lalaque Mine - Battle 5", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 6", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 11", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 12", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 13", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 14", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 15", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 16", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 17", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 18", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 19", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 20", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 24", has(world, "Chaos Stone"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 25", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 26", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 27", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lalaque Mine - Battle 28", has(world, "Chaos Stone"))
    safe_set_location_rule(world, "Laoba Mountain - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Laoba Mountain - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Laoba Mountain - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 4", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Lions Plain - Battle 5", has(world, "Chapter 3"))
    safe_set_location_rule(world, "North Merchant Road - Battle 2", has(world, "Boar Captain's Tooth"))
    safe_set_location_rule(world, "Pudding Cave 2 - Battle 1", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave 2 - Battle 2", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave 2 - Battle 3", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave 2 - Battle 4", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Pudding Cave - Royal Pudding - Battle 1", has(world, "Aged Lalaque Berry"))
    safe_set_location_rule(world, "Shipwreck - Battle 1", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Shipwreck - Battle 2", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Shipwreck - Battle 3", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Shipwreck - Battle 4", lambda state: state.has("Chapter 4", world.player) and state.has("Shipwreck Brig Key", world.player))
    safe_set_location_rule(world, "Shipwreck - Battle 6", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player))
    safe_set_location_rule(world, "Shipwreck - Battle 7", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Snow Field - Battle 1", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 2", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 3", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 4", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 5", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 6", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 7", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 8", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 9", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 10", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 11", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 12", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 13", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 14", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 15", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 16", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 17", has(world, "Chapter 6"))
    safe_set_location_rule(world, "Snow Field - Battle 18", has(world, "Chapter 6"))
    safe_set_location_rule(world, "South Island - Battle 1", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 2", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 3", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "South Island - Battle 5", has(world, "Chapter 5"))
    safe_set_location_rule(world, "South Island - Battle 6", has(world, "Chapter 2"))
    safe_set_location_rule(world, "South Island - Battle 7", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Swamp - Battle 2", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 3", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 5", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Swamp - Battle 6", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 7", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 8", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 9", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 10", has(world, "Mind Control Circle"))
    safe_set_location_rule(world, "Swamp - Battle 11", has(world, "Chapter 2"))
    safe_set_location_rule(world, "Swamp - Battle 12", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Swamp - Battle 13", has(world, "Chapter 5"))
    safe_set_location_rule(world, "Vavelia Road - Battle 1", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 2", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 3", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 4", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 5", has(world, "Chapter 4"))
    safe_set_location_rule(world, "Vavelia Road - Battle 6", has(world, "Chapter 3"))
    safe_set_location_rule(world, "Vavelia Road - Battle 7", has(world, "Chapter 3"))
    # === END Battlesanity (generated) ===
    # === BEGIN Bestiary (generated) ===
    safe_set_location_rule(world, "Bestiary - Big Frog", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Boar Junior", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Bestiary - Black Joe", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Flame Dwarf Golem", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Small Wild Boar Golem", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Tiny Combat Golem", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Junior Plains Boar", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Bestiary - Lalaque Village Warrior", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Bestiary - Small Dwarf Golem", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Wild Dog", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Giant Blue Crab", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Giant Frog", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Lalaque Village Archer", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Magmata", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Small Combat Golem", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Bomb Spider", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Wampleaf", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Bestiary - White Dwarf Golem", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Grown-up Dwarf Golem", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Seed Spirit", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Broad Dwarf Golem", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Rogue Rabbit", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Crow", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Jack-in-the-box", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Tiny Volcanic Golem", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Lightning Blue Crab", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Bandits Captain Kanna", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - White Fox", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Red Hawk", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Steam Launcher", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Tainted Carico", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Mid-Rank Lalaque Warrior", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Stone Fox", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Tiny Demon", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Bestiary - Low-Rank Dark Palace Warrior", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Boar Golem", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Bestiary - Ugly Bird", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Laquerak", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Leaf Golem", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Bestiary - Mid-Rank Palace Warrior", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Carico", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Boar Captain", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Bestiary - Hedgehog Rock", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Livya", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Bestiary - Giant Wampleaf", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Defensive Mid-Rank Palace Warrior", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Demon of Greed", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Ugly Birds Captain", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Eison", lambda state: state.has("Chapter 2", world.player) and state.has("Aged Lalaque Berry", world.player))
    safe_set_location_rule(world, "Bestiary - Goat Statue", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Tia Reese", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Tia Reet", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Tia Rion", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Steam Golem 003", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Balt", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Dark Lion", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - High-Rank Palace Warrior", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Poison Golem", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Lucca", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Buffalo Gorilla", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Tiny Giant", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Steam Golem 002", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Bestiary - Horned Deer", lambda state: state.has("Chapter 6", world.player) and state.has("Soul Sword", world.player))
    safe_set_location_rule(world, "Bestiary - Dark Mid-Rank Palace Warrior", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player))
    safe_set_location_rule(world, "Bestiary - Justice", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - Pudding Queen", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Fire Demon", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Bestiary - Nekomis", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Ancient Lightning Dragon Junior", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Fire Frog", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Royal Palace Special Forces Warrior", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Big Crab", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Pudding King", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Caric", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Bestiary - White Rhino", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Brillion", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Big Stone Golem", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Demon King", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Bestiary - Angry Fluoride", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Yeti", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Water Balloon Frog", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Lava", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Luna", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Red Demon King", lambda state: state.has("Chapter 3", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Bestiary - Dark High-Rank Palace Warrior", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - High-Rank Elite Warrior", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Verstein", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Giant Palace Golem", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Schwitz", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Curse Executor", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Zircon Dragon", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Supreme Warrior", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Bestiary - White Giant", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Bestiary - Tainted Mutated Nuuk", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Aslan", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Bestiary - Crown", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Durok Temple Statue", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Ancient Garden Wampleaf", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Bestiary - Hunt Executor", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Ice Giant", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Old Yeti", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Lightnoceros", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Tainted Darkstone Cave Giant", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Shipwreck Beruch", lambda state: state.has("Chapter 4", world.player) and state.has("Shipwreck Brig Key", world.player))
    safe_set_location_rule(world, "Bestiary - Lightning Dragon", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Harvest Executor (WhiteCutter)", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Bestiary - Zirconia Dragon", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Bestiary - Black Yeti", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Aeris", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Ancient Lightning Dragon", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Bestiary - Blast", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Bestiary - Narrel", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Temar", lambda state: state.has("Chapter 6", world.player))
    safe_set_location_rule(world, "Bestiary - Jade", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    # === END Bestiary (generated) ===
    # === BEGIN QuestSanity (generated) ===
    safe_set_location_rule(world, "Quest - Visiting Anna's House", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Temple Trial", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Sneaking Past the Warriors", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Door to the Outside World!", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Giant Bird", lambda state: state.has("Chapter 4", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Searching for the Intruder", lambda state: state.has("Chapter 6", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Runaway Black Joe!", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Checking on Anna", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Temple Investigation", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Investigating the Snow Field Entrance", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Island Investigation", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Returning the Commander's Insignia", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Crown Vs Excuter", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Nuuk Field Outlaw", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - Delivering the Chaos Stone to Anna", lambda state: state.has("Chapter 2", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Giving Kanna the Engine", lambda state: state.has("Chapter 5", world.player) and state.has("Prototype Steam Engine", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Durok's Spring", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Eternal Ice", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Fighting Wounded Warrior", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Infiltrating the Pope's Castle", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Quest - Strawberries Hunt in the Boar Plain", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Quest - Helping Kanna", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Quest - Finding the Children of Lalaque", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Investigating Shipwreck", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Finding Red Beard's Lair", lambda state: state.has("Chapter 5", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Listening to Reina", lambda state: state.has("Chapter 5", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Saving David", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Going to Durok Temple", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Searching for Strawberries!", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Quest - Ready for War", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Quest - Shipwreck  Commander's Cabin", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player))
    safe_set_location_rule(world, "Quest - Homeward Bound", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Quest - All Aboard!", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Quest - Exploring Aimhard Temple", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Entering the Snow Field", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Visiting Kanna's House", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Defeating the Ice Giant", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Exploring Backhill Golem Cave", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Quest - Leaving Matt's Garden", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Finding the Pie Maker!", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Finding Luna's House", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Darkstone Cave", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - Return to Ralph!", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Quest - First Trade with Ralph", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Thief!", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Quest - Prison Break", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Let's Go Outside!", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Leaving Calzvero Forest", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Gorrila Grass", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Finding Sara", lambda state: state.has("Chapter 5", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - High Level Armor Ore", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Reporting to Verstein", lambda state: state.has("Chapter 5", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Sharing Results with Verstein", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Telling Kanna the News", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Kate And Livya", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Finding the Pie Maker in Lalaque Village", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Tracking the Bomb Witch", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Legend Pudding", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Exorcizing the Evil Demons in the Village", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Collapsed Justice", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Riding a Nuuk", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - Connecting the Mine to the House", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Anna's Advice", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player))
    safe_set_location_rule(world, "Quest - Following Alfredo!", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Finding Anna", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - Anxious Anna", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player))
    safe_set_location_rule(world, "Quest - Finding the Chaos Stone", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Entrance to Elysion Temple", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - Tracking Down Justice", lambda state: state.has("Chapter 5", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Finding Kate's Sibling", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Thorough Exorcism", lambda state: state.has("Chapter 2", world.player) and state.has("Lalaque Mine Key", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - To Aimhard Temple", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - To Elysion Temple", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - West of Elysion Plain", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - Going to the Snow Field", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Reassuring Anna", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Informing Anna", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - Barrier Wall", lambda state: state.has("Chapter 3", world.player) and state.has("Dispelling Stone", world.player, 4) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Discovered Anna", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player) and state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Warrior Sweep", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Finding Memories", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - Let's Try Mind Control!", lambda state: state.has("Mind Control Circle", world.player))
    safe_set_location_rule(world, "Quest - Even Better Magic!", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Learning Ice Magic", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Magic Spellbook", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Narer Ralph", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Quest - New Clothes", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - Passing Arua's Test", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Blue Crab Cover", lambda state: state.has("Chapter 3", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Fire Stone", lambda state: state.has("Chapter 3", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Iron Ore", lambda state: state.has("Chapter 3", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Iron Ore 2", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Leaf Mini Golem", lambda state: state.has("Chapter 3", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Pudding", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Warriors Sword Thunder Material", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Ralph Quest Warriors Sword Thunder Material 2", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Power to Protect", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Behind Bars", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Red Beards Package Arrives", lambda state: state.has("Chapter 5", world.player) and state.has("Secret Trader Key", world.player))
    safe_set_location_rule(world, "Quest - Delivering Strawberries", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Get Some Sleep", lambda state: state.has("Chapter 2", world.player))
    safe_set_location_rule(world, "Quest - Sleep And Go To Balt", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - The War Begins", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Quest - Suspicious Shipwreck Key", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player))
    safe_set_location_rule(world, "Quest - Suspicious Cave", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Exploring the Village", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - Suspicious Justice", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Memories of the Past", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - Temar's Trial", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Alfredo the Thief", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player) and state.has("Chaos Stone", world.player) and state.has("Lalaque Mine Key", world.player))
    safe_set_location_rule(world, "Quest - To Aramute Spring", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Quest - Discovering Elysion Temple", lambda state: state.has("Chapter 4", world.player))
    safe_set_location_rule(world, "Quest - Father's Grave", lambda state: state.has("Chapter 7", world.player))
    safe_set_location_rule(world, "Quest - Tracking the Bandits", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Tracking Wounded Warrior", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Waiting for Luna", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - War Horn", lambda state: state.has("Chapter 3", world.player) and state.has("Chaos Stone", world.player))
    safe_set_location_rule(world, "Quest - Warrior Magic Weapon", lambda state: state.has("Chapter 6", world.player) and state.has("Ice Witch Scarf", world.player))
    safe_set_location_rule(world, "Quest - Hurried Review", lambda state: state.has("Chapter 3", world.player) and state.has("Shipwreck Hold Key", world.player) and state.has("Rusty Commander's Cabin Key", world.player) and state.has("Matt's Garden Passage Key", world.player))
    safe_set_location_rule(world, "Quest - Exploring Elysion Temple", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Checking on Justice 2", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Checking on Justice", lambda state: state.has("Chapter 5", world.player))
    safe_set_location_rule(world, "Quest - Investigate Lalaque Forest", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Spying on Livya", lambda state: state.has("Chapter 3", world.player))
    safe_set_location_rule(world, "Quest - Matt's Garden", lambda state: state.has("Chapter 2", world.player) and state.has("Boar Captain's Tooth", world.player))
    safe_set_location_rule(world, "Quest - Exploring the Outside World", lambda state: state.has("Mind Control Circle", world.player) and state.has("Fire Magic Spellbook", world.player))
    safe_set_location_rule(world, "Quest - Exploring the Wreck", lambda state: state.has("Chapter 3", world.player))
    # === END QuestSanity (generated) ===
def set_completion_condition(world) -> None:
    goal_choice = int(world.options.goal_choice.value)
    #world.set_completion_rule(HAS_ICE_SPELLBOOK)
    world.multiworld.completion_condition[world.player] = has(world, f"Chapter {goal_choice}")
    #world.multiworld.completion_rule(has(world, "Ice Magic Spellbook"))